### ISSUE TITLE
Notification readme

### ISSUE THREAD

**Issue by netwrkx** [viralsolani/laravel-adminpanel#113]
I observed this project has notification system, but its not written on the readme.
Can you please update the readme on what to expect from the notification system or how it works. Thanks

**Comment by netwrkx** [comment]
It look like I understand how the notification works but the class ".notification-counter",  ".notification-menu-container" hasn't been attached to the header file. 
Summary: The notification counter & the notification result isn't showing

**Comment by viralsolani** [comment]
@netwrkx Yes, we want to remove this old notification logic with the new Laravel Notification.
