### ISSUE TITLE
Just a thanks and tests

### ISSUE THREAD

**Issue by bloggervista** [viralsolani/laravel-adminpanel#123]
Can we write tests. Rappsoft boilerplate has some failing test i hope we can solve it.

And thanks for these upgrades :)

**Comment by bvipul** [comment]
Yes, @bloggervista, we would be happy to seek your help, as we are writing our tests. And we hope this project helped you and you are willing to help us out is a great gesture.

**Comment by bloggervista** [comment]
Yea will surely help you :)

Thanks was searching it for long time :)
