### ISSUE TITLE
Can we use package instead of unsupported access for permissions and history

### ISSUE THREAD

**Issue by bloggervista** [viralsolani/laravel-adminpanel#131]
As rappsoft has already decided he isn't going to support for access i guess we also can go for spatie permissions or other package and he has removed history also? Can we do something about that?

**Comment by bvipul** [comment]
We are also thinking about the same, but we are currently busy in writing test cases. But sure that is up for consideration.

**Comment by viralsolani** [comment]
Yes, we want to use spatie's package in future. But before that, we need to think about better UI to assign permission at the time of creating user and role.

**Comment by bloggervista** [comment]
there is already one done by rappsoft in latest version of it.

Regarding test if we replace many by package i guess test will be reduced to half right?

**Comment by viralsolani** [comment]
Well, Yes I've checked the latest version of Laravel 5 Boilerplate. It is very good. But the only issue if we have many permission we need scroll and it will be hard to find one. 

So I think we can use jstree or something similar. 

No test will not be reduced because in our version we will keep permission module.

**Comment by bloggervista** [comment]
For scroll we can use select2 ?

**Comment by trollid** [comment]
+1 for spatie and select2

**Comment by viralsolani** [comment]
Ok once we complete writing test cases, we want to use vue.js in the application. and with that we will use spatie's permission package for sure.

**Comment by bloggervista** [comment]
@viralsolani  which which tests are missing may be we can help

**Comment by viralsolani** [comment]
@bloggervista you can write test cases for email template and faq module.

**Comment by viralsolani** [comment]
@bloggervista if I or @bvipul get chance to complete it before 10th we will do it or you can work on that. we will update you. Thanks.
