### ISSUE TITLE
Do we need tags?

### ISSUE THREAD

**Issue by bloggervista** [viralsolani/laravel-adminpanel#143]
It seems they both are serving same purpose isn't it ?

I guess it is good to support if categories are hierarchical like in wordpress otherwise there are just same under different name in current scenerio right?

**Comment by viralsolani** [comment]
Yes Right. we can use jsTree or something related in vue.JS. I'm leaning vue.js as of now and want to remove all jquery and replace it with vue.js.

We kept tag and category both as admin may want to edit at some point so he can do that from admin panel.

**Comment by bloggervista** [comment]
@viralsolani  yes exactly . I used vue js and all the jquery based function stopped in admin panel. I guess it won't take even a week to learn vue. Laracasts and Udemy one is really great :)

Have fun learning vue :)
