### ISSUE TITLE
CMS Pages Not Showing on Front Side

### ISSUE THREAD

**Issue by krishu-25** [viralsolani/laravel-adminpanel#144]
Thank you for your great admin panel, How can i display the backend register CMS pages display on Frontside. When i call the route like (i.e http://localhost:8000/cmspage/terms-and-conditions) give me error like below , Please provide some brief description for that. Here below i have to attached screen shot for the error.
![whoops there was an error](https://user-images.githubusercontent.com/35991744/35612945-76a979ea-0690-11e8-849c-ec10a58eae74.png).

Thank You.

**Comment by bvipul** [comment]
Hello @krishu-25 ,
sorry, this seems to be a typo in App\Repositories\Frontend\CMSPages\CMSPagesRepository.
What you need to is change "use App\Models\CMSPages\CMSPage" to "use App\Models\Page\Page".
I will create a patch PR for that , thank you for letting us know.

**Comment by bvipul** [comment]
Hello @krishu-25, I have added a PR for this issue. thanks for letting us know.
#145

**Comment by krishu-25** [comment]
@bvipul  @viralsolani I would really appreciate if you guys will share step-by-step guide to create new CRUD screen along with permssions.

**Comment by viralsolani** [comment]
@krishu-25 ok sure. we will soon add that in to our readme file.

**Comment by bvipul** [comment]
@viralsolani @krishu-25 I think I should create a video for that. I think I would do that.

**Comment by krishu-25** [comment]
@bvipul  That's **great** news. When you are able to publish those videos?

**Comment by bvipul** [comment]
@krishu, soon is what I can say. Probably next week

**Comment by trollid** [comment]
@bvipul @viralsolani thanks a lot, i think i lost my way, need tutorial
thanks guys

**Comment by bvipul** [comment]
Will soon publish the video for this. For now closing this ticket.
