### ISSUE TITLE
Create data with null value ????

### ISSUE THREAD

**Issue by nguyenkhoi2806** [viralsolani/laravel-adminpanel#158]
When i fill all input in a form and click create, it save with null value but Edit is ok

**Comment by nguyenkhoi2806** [comment]
I fixed. Thanks your CMS

**Comment by indranshastri** [comment]
Thank you for the info 
But can u explain in detail about the issue (like Where did you got the issue,How did you resolve the issue)

**Comment by viralsolani** [comment]
@nguyenkhoi2806 if you resolve any error then please send pull request or please close this issue.
