### ISSUE TITLE
Css template admin not display like ScreenShots picture

### ISSUE THREAD

**Issue by nguyenkhoi2806** [viralsolani/laravel-adminpanel#193]
![imgpsh_fullsize](https://user-images.githubusercontent.com/16773113/37762488-025d0dfa-2def-11e8-90d6-06fea65c5f1a.jpg)

**Comment by bvipul** [comment]
@nguyenkhoi2806 this seems like an error somewhere, happened to someone else also. We will surely look into this. Thanks for reporting.
Just to make our process easier, could you please tell us these things below:
1. PHP version
2. Node and npm version
3. Your OS and its version (like Ubuntu 16.04, Windows 7 etc)
4. And other error or notices you might end up seeing while doing the steps to install this project on your machine.

Thanks so much.

**Comment by nguyenkhoi2806** [comment]
thanks your reply
my php-version: 7.2
node 9.9 
npm 5.6.0
os ubuntun 16.04
Error when npm install : 
-Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8
-Command failed: autoreconf -fiv
/bin/sh: 1: autoreconf: not found

**Comment by nguyenkhoi2806** [comment]
Hi guy i resolved it. My public folder is missing some js and css file Sorry about this issue

**Comment by bvipul** [comment]
Thank you so much, @nguyenkhoi2806 can you please elaborate what was the issue?

**Comment by nguyenkhoi2806** [comment]
In my public directory is missing some files from your public directory
Sorry my English is not good

**Comment by bvipul** [comment]
@nguyenkhoi2806  how can that happen, if you have taken clone of our project, then everything should come from repo itself.

**Comment by viralsolani** [comment]
I think @nguyenkhoi2806  may not run npm run development so build files are not generated.

**Comment by nguyenkhoi2806** [comment]
No No it' work  good,  when i clone from your repo. but when i commit with my new repo. It didn't commit some css and js file so when run npm development, it doesn't compile all. :)

**Comment by viralsolani** [comment]
ok cool. closing this issue now.
