### ISSUE TITLE
El contenido del #showMenuModal desaparece despues de un cierto tiempo

### ISSUE THREAD

**Issue by michini** [viralsolani/laravel-adminpanel#195]
Hola amigo, el problema es que al hacer click en el boton **Add Custom URL** o en el **boton de editar menu**, se muestra el modal primeramente con el error **Something went wrong! Please try again later.** y en segundo click sale el formulario que solo dura un cierto tiempo luego se pone la clase hidden.

**Menus:**
![image](https://user-images.githubusercontent.com/9531905/38013138-abd0ebca-3229-11e8-9d65-376e89c6dc99.png)

**Primer click**
![image](https://user-images.githubusercontent.com/9531905/38013026-3f641c78-3229-11e8-8e83-72a4f08ad074.png)

**Segundo click**
![image](https://user-images.githubusercontent.com/9531905/38013056-5b8f884c-3229-11e8-94ac-98af97082053.png)

**y por ultimo desaparece el contenido del modal**
![image](https://user-images.githubusercontent.com/9531905/38013090-7349619c-3229-11e8-9015-788f5ce9f4c1.png)

espero tu ayuda, gracias.

**Comment by bvipul** [comment]
I know this is a problem but what you need to do solve this is to change some code on ``resources/views/backend/menus/form.blade.php``.
On line 188, you will find a click event and inside that event closure, you can find that there is a setTimeout function called and has 500 as the second parameter, you need to increase that value to 1500 or 2000. And then try to achieve the same.
Do tell if you further face the same problem.

**Comment by bvipul** [comment]
Hello @michini, we have updated our master branch which solves this error. Please take pull from master and see if it resolves your problem.

Please reopen this issue, if you still face it.
