### ISSUE TITLE
Use Bootstrap 4 for Frontend

### ISSUE THREAD

**Issue by jebog** [viralsolani/laravel-adminpanel#200]
Hello, thanks for your Great Work, Can you help me ? I want to keep Bootstrap 3 for Backend and replace it on frontend with Bootstrap 4. Is there a way to manage with it quickly ?

**Comment by viralsolani** [comment]
@jebog Thanks. As of now we are focusing on API and integrating vue.js and our next goal is to integrate core UI which have bootstrap 4. 

We have checked it already After using Bootstrap 4 , we need to change in class name that we have used in our blade files.

**Comment by bvipul** [comment]
Sorry @jebog, this is currently not possible, as we can only have one version of Bootstrap to be used on both backend and frontend. 

If we change the dependency to bootstrap 4, then backend also needs to be converted to bootstrap4.

So, the answer to your question is No.
