### ISSUE TITLE
solve it

### ISSUE THREAD

**Issue by shahnoorkhowaja** [viralsolani/laravel-adminpanel#205]
![image](https://user-images.githubusercontent.com/25455321/38657732-49288654-3e3b-11e8-9af3-c5efaf3eddaf.png)

**Comment by viralsolani** [comment]
@shahnoorkhowaja  Have you run php artisan db:seed ?

**Comment by shahnoorkhowaja** [comment]
yes

**Comment by viralsolani** [comment]
Have you create .env and mention your username and password to access database cred.

**Comment by jebog** [comment]
It's looks like database server connection failed. check username and  password or if your database service is running

**Comment by bvipul** [comment]
@shahnoorkhowaja is your problem resolved? I also think either your db service is not running or your username/password is wrong in .env.

**Comment by viralsolani** [comment]
Please re-open this ticket if you have any issues in future.
