### ISSUE TITLE
Issue when open url in browser

### ISSUE THREAD

**Issue by truelogicapp** [viralsolani/laravel-adminpanel#207]
ErrorException (E_ERROR)
The Mix manifest does not exist. (View: C:\xampp\htdocs\udrive1.0\resources\views\frontend\layouts\app.blade.php) (View: C:\xampp\htdocs\udrive1.0\resources\views\frontend\layouts\app.blade.php)
![image](https://user-images.githubusercontent.com/5255112/38922313-f1bed5bc-4308-11e8-8f24-d8aa0752e6bf.png)

**Comment by bvipul** [comment]
You can run `npm run dev` to solve this issue.

**Comment by bvipul** [comment]
I think this issue can be closed.
