### ISSUE TITLE
 The assignment of permissions to the respective roles does not work

### ISSUE THREAD

**Issue by worrabroshnot** [viralsolani/laravel-adminpanel#210]
when permissions are assigned to roles, it does not take them into account, unless it is indicated that they have all the permissions.

**Comment by bvipul** [comment]
In our adminpanel, what we have done is, If you add or remove a permission from a role, it won't change the permissions of every user associated with that role, but it will give priority to the individual permissions of the user. But when a new user is created for the changed role, it will have all the permissions for the role. I hope this solves your query. Reply back if that isn't the case.
