### ISSUE TITLE
[Question] How is Email Template Model, Repository Used?

### ISSUE THREAD

**Issue by bloggervista** [viralsolani/laravel-adminpanel#212]
Checked code found all reset etc are done via $user->notify like that so how are those used thanks?

**Comment by bvipul** [comment]
Sorry, I was not able to understand your question, could you please elaborate?

**Comment by bloggervista** [comment]
i mean where are those EmailTemplateModel etc used?

i mean if we go to admin/emailtemplates we will see user registration etc.. at which part of code they are used . Because i see code using only notifications etc.

**Comment by bvipul** [comment]
okay, so the email templates are being used at several places, like for frontend user, when he changes password, a mail is send which uses one of email templates to send the email. You can see the code in UserRepository for frontend. And mail sending code is in sendEmail.php Utility.

**Comment by bloggervista** [comment]
@bvipul  in Frontend UserRepository i see only such codes `$user->notify(new UserNeedsConfirmation($user->confirmation_code));` which uses notifications to send email etc.. Can you give me line no where it is used?

Thanks

**Comment by bvipul** [comment]
@bloggervista Yes I can. You can go to app/Repositories/Frontend/Access/User/UserRepository.php, and go to line 301, which has a function called createNotification(), which is defined in helpers, which is responsible for sending email with email templates.
Thanks.

**Comment by bloggervista** [comment]
@bvipul  thanks
