### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by afoysal** [viralsolani/laravel-adminpanel#217]
How to add custom CSS in this admin panel?

**Comment by viralsolani** [comment]
@afoysal  you can write your custom css in _public/css/backend/backend-custom.css_. 

We have already  written few CSS there.

**Comment by afoysal** [comment]
https://i.stack.imgur.com/rEtZv.png

**Comment by viralsolani** [comment]
@afoysal you can create your own custom CSS and include in the layout. please let me know if you have any queries or concerns.
