### ISSUE TITLE
registration not working

### ISSUE THREAD

**Issue by nithiyakumark** [viralsolani/laravel-adminpanel#219]
hi, i'm trying to register an account but its not working even its not throwing any error

**Comment by viralsolani** [comment]
@nithiyakumark Can you please report errors? If possible please provide screenshots?

**Comment by pervaiz04** [comment]
same error with me - unable to register - no error - page refresh - seems not going in controller register function

**Comment by pervaiz04** [comment]
alsi i am seeing this error
[Vue warn]: Unknown custom element: <flash> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)

**Comment by bvipul** [comment]
Yes, @pervaiz04, thanks for pointing the issue, I will be resolving that in our next release.

**Comment by vrkansagara** [comment]
@nithiyakumark and @pervaiz04 Kindly confirm the issue is still there.

**Comment by pervaiz04** [comment]
Thank you for fixing,
I'll check shortly

Thanks
