### ISSUE TITLE
Method selectStateUS does not exist. 

### ISSUE THREAD

**Issue by vrkansagara** [viralsolani/laravel-adminpanel#233]
By visiting this url `http://127.0.0.1:8000/macros`

Does maintainer forget to add any dependency?

**Comment by bvipul** [comment]
We have removed the macros completely from our project in our last release, I guess we have left that route. Thanks for pointing that out. If you want to create a PR resolving this, you can, but just remember to push that change to `develop` branch.

**Comment by viralsolani** [comment]
@vrkansagara Resolved. Thanks for pointing out the issue.
