### ISSUE TITLE
Proposal for api formatter

### ISSUE THREAD

**Issue by vrkansagara** [viralsolani/laravel-adminpanel#235]
I would like to purpose api formatter for the API layer.

- User can able to define their own response formate based on sample.
- Response formate in various formate , JSON, XML, JSONP
- Response formate based on [HAL JSON](http://stateless.co/hal_specification.html)

**Comment by viralsolani** [comment]
@vrkansagara ok let me check. then we will discuss about it.

**Comment by viralsolani** [comment]
@vrkansagara good concept. let's work on it to gather.
