### ISSUE TITLE
 $ is not defined, jQuery is not defined in console tab in front end ???? 

### ISSUE THREAD

**Issue by nguyenkhoi2806** [viralsolani/laravel-adminpanel#243]
![screenshot from 2018-07-01 12-09-14](https://user-images.githubusercontent.com/16773113/42131225-9e2641d4-7d27-11e8-9328-b7a39d84cf9b.png)

**Comment by nguyenkhoi2806** [comment]
I Fixed thanks you

**Comment by viralsolani** [comment]
Please send the pull request.

**Comment by viralsolani** [comment]
@vrkansagara Can you please look into this?

**Comment by vrkansagara** [comment]
@viralsolani I am looking into this matter.

**Comment by vrkansagara** [comment]
@nguyenkhoi2806  Can you share us your `app.blade.php` layout file. It's look like that `jquery` not loaded with dome load.

You have to make sure that `jQuery` is loaded before any jquery function execute.
