### ISSUE TITLE
Datatable export buttons not workig in new generated module

### ISSUE THREAD

**Issue by umair321** [viralsolani/laravel-adminpanel#248]
I have generated module, but export buttons for datatable not working. I have matched code with user/index.php datatable.
![eeeeee](https://user-images.githubusercontent.com/7020208/43317302-c176d7c8-91b5-11e8-8eff-3d36f4625d77.png)

**Comment by bvipul** [comment]
Please see to it that do you have some console errors on the page @umair321 ?

**Comment by umair321** [comment]
No there is not a single console error or warning

**Comment by bvipul** [comment]
Okay, great. @umair321
