### ISSUE TITLE
Cant Run Frontend.

### ISSUE THREAD

**Issue by Jyotie** [viralsolani/laravel-adminpanel#249]
Hello I setup the project locally as per given instructions.
And now running the site.
This is my URL: http://localhost/PROJECTS/laravel_adminpanel/public/frontend

But it shows me Page Not Found error.

Symfony\Component\HttpKernel\Exception\NotFoundHttpException

How can I fix this?

**Comment by bvipul** [comment]
You need to run the server, `php artisan serve` in the project folder and check at localhost:8000

**Comment by christiantigre** [comment]
Delete fronted.
http://localhost/PROJECTS/laravel_adminpanel/public/

**Comment by bvipul** [comment]
That is not the preferred way, run the artisan server or make vhost. The simplest way will be to run the server.

**Comment by bvipul** [comment]
I guess, this issue can be closed. Feel free to reopen.
