### ISSUE TITLE
site logo

### ISSUE THREAD

**Issue by AManojKiran** [viralsolani/laravel-adminpanel#253]
I have uploaded the site logo but it is not displaying

**Comment by bvipul** [comment]
You will probably have to see if you created the link to storage folder. 
For that, you need to do `php artisan storage:link`. Try this, and then reload and tell us if your problem is resolved or if it's still there. @AManojKiran

**Comment by bvipul** [comment]
Try adding this to the src of the image path: `{{ Storage::disk('public')->url('img/logo/' . $settings->logo) }}` and it should work

**Comment by stoneshaq** [comment]
{{ Storage::disk('public')->url('img/logo/' . $setting->logo) }} is already there..

Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost/storage/img/logo/logo.jpg with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by krishnabharambe** [comment]
CTRL + F5

**Comment by brazitech** [comment]
yes i did. also i use an apple for development and also use valet and not artisan serve.

**Comment by bvipul** [comment]
Is it a Mac issue? @AManojKiran and @stoneshaq, do you guys also use Mac?

**Comment by brazitech** [comment]
just found the problem. in the .env you have to use the actual url and not localhost. storage facade  uses APP_URL env variable.in my case APP_URL=http://LDSag.loc not APP_URL=localhost.

**Comment by bvipul** [comment]
Oh great, so it is working?

**Comment by brazitech** [comment]
yes it is. thank you for answering on a Sunday...glad to see i not the only one that work today....:-)

**Comment by bvipul** [comment]
Yes, @stoneshaq, you probably will have the same issue, your comment states, it was using localhost for fetching the image and your site would be running on localhost:8000 or on a different url, that's why the issue. Please confirm, so I can close this issue
