### ISSUE TITLE
conformation email

### ISSUE THREAD

**Issue by brazitech** [viralsolani/laravel-adminpanel#257]
i cant find where to enable the conformation email on registration. is it to be added to the .env?

**Comment by viralsolani** [comment]
Yes, you can do that from .env. You need to make REQUIRES_APPROVAL=true.

Please find the attached screenshot

![image](https://user-images.githubusercontent.com/1780168/45312437-acbb5b80-b549-11e8-8d45-91afe53f428c.png)

**Comment by brazitech** [comment]
i added the requires approval true it still does not work.. it will send the forgot password email, but not the conformation email. is there something else that needs activation?

**Comment by viralsolani** [comment]
I'll check and get back to you about this feature.

**Comment by lili94** [comment]
do you find solution i have the same problem

**Comment by mehadihasan** [comment]
any solutions?

**Comment by bvipul** [comment]
@mehadihasan @lili94 @brazitech Have you setup the smtp credentials in .env ?

**Comment by mehadihasan** [comment]
yes, I used Gmail smtp credentials and its working.

**Comment by bvipul** [comment]
Awesome, so I am closing this issue.

**Comment by lili94** [comment]
hi @mehadihasan  can you put some capture how you fixed it or help me please

**Comment by mehadihasan** [comment]
hello @lili94 
Use mail setup in .env

MAIL_DRIVER=smtp
MAIL_HOST=your host
MAIL_PORT=your port
MAIL_FROM=your mail id
MAIL_FROM_NAME=mail from
MAIL_USERNAME=your username
MAIL_PASSWORD=your password
MAIL_ENCRYPTION=your mail encryption

try it for the forgot password option, hope it will work. If not, then let me know.
