### ISSUE TITLE
pgsql (postgresql) error clean installation

### ISSUE THREAD

**Issue by corepay** [viralsolani/laravel-adminpanel#258]
Hi, using pgsql with fresh installation and getting datatables error.  Switching to mysql no problems.

![image](https://user-images.githubusercontent.com/37046197/45311814-507c1b80-b4f8-11e8-8d70-c304a0b958a8.png)

![image](https://user-images.githubusercontent.com/37046197/45311846-73a6cb00-b4f8-11e8-8af5-602e64ba24da.png)

**Comment by viralsolani** [comment]
@corepay we have used Raw MySQL queries in this application for grid part. you need to convert those to PGSQL.

**Comment by corepay** [comment]
Got it, thanks.  MySql is good for now.  Looks good though!
