### ISSUE TITLE
Undefined index: /css/frontend.css

### ISSUE THREAD

**Issue by IhsanBhee** [viralsolani/laravel-adminpanel#266]
Hi,
I'm trying to running laravel-adminpanel, but i have found error this Undefined index: /css/frontend.css in laravel-adminpanel\resources\views\frontend\layouts\app.blade.php. What can i do to resolve this issue.

Thanks
Febri

**Comment by viralsolani** [comment]
Hello @IhsanBhee Are you able to successfully run _npm run development_ ? Can you please give us some screenshot so that we can identify the issue.

**Comment by IhsanBhee** [comment]
This my Issue
![issue](https://user-images.githubusercontent.com/8456061/46456524-17f1f980-c7a7-11e8-8b00-aa9b90ed2c08.PNG)

**Comment by viralsolani** [comment]
@IhsanBhee Can you please give me your node version. and also check you npm log. you will get more idea.

**Comment by IhsanBhee** [comment]
this using Node and Npm version :
info using npm@6.4.1
info using node@v8.12.0

**Comment by vrkansagara** [comment]
@IhsanBhee  Kindly remove your node_modules folder and re-run the `npm i  && npm run development`

**Comment by viralsolani** [comment]
@IhsanBhee are you still facing issue? if not then please close this issue.

**Comment by IhsanBhee** [comment]
I will trying sir.

Pada tanggal Kam, 11 Okt 2018 01:39, Vallabh Kansagara <
notifications@github.com> menulis:

**Comment by IhsanBhee** [comment]
[image: image.png]

[image: image.png]

still same error. Or need change version node and npm

Pada tanggal Jum, 12 Okt 2018 pukul 10.50 Febri Hasan <88ihsan@gmail.com>
menulis:

**Comment by bvipul** [comment]
can you please update, if your issue has been resolved. Because these kind of issues, mostly solve itself.

**Comment by vrkansagara** [comment]
It's look like issue resolved. closing down.
