### ISSUE TITLE
The Mix manifest does not exist

### ISSUE THREAD

**Issue by ash94ish** [viralsolani/laravel-adminpanel#267]
I am getting this error
"The Mix manifest does not exist. (View: C:\xampp\htdocs\laravel-adminpanel\resources\views\frontend\layouts\app.blade.php) (View: C:\xampp\htdocs\laravel-adminp ▶"

![image](https://user-images.githubusercontent.com/9510757/46584659-938fc700-ca83-11e8-9625-9c267ddb0387.png)

**Comment by vrkansagara** [comment]
this is duplicate issue #227. @viralsolani , @bvipul  close it.

@ash94ish kindly look for the closed issue first before issuing new one which help you to quickly jump on already solved problem which lead into saving time and delay in response.

**Comment by vrkansagara** [comment]
@ash94ish  The quick response is you have to run `npm run development`

**Comment by viralsolani** [comment]
@ash94ish Yes if you run the above command it will sure resolve your issue.

**Comment by kumawatram** [comment]
After run all these command and also generate the file, But public_path given some error .
Am attach the screen.

![image](https://user-images.githubusercontent.com/12869568/48313047-1228d880-e5dd-11e8-9fa3-83408a541cb6.png)


now am print the public_path : out put is 

E:\xampp\htdocs\laravel-adminpanel/../public\/mix-manifest.json

please suggest me.

Also i want to run this code on root.

Am new in laravel.

**Comment by vrkansagara** [comment]
@kumawatram I would suggest to follow https://github.com/viralsolani/laravel-adminpanel/issues/267#issuecomment-428684179
