### ISSUE TITLE
I want to ask...

### ISSUE THREAD

**Issue by xiashiwei** [viralsolani/laravel-adminpanel#268]
Sir,I want to ask why not use bootstrap4 as the default frontend scaffold?
![20181010141535](https://user-images.githubusercontent.com/7830327/46716909-5f412400-cc98-11e8-9f4e-330f70187519.png)

**Comment by vrkansagara** [comment]
@xiashiwei  It is a good question. I assume this is developed for long term stability so we have used this. But still you are feel free to implement on your fork and send us PR for further review and merge process.

I hope this convey to you. @viralsolani , @bvipul you can tag as enhancement tag and close it.

**Comment by viralsolani** [comment]
@xiashiwei Yes, it is in the plan. we will do it in near future.
