### ISSUE TITLE
Issue With Datatable

### ISSUE THREAD

**Issue by hanabishirin** [viralsolani/laravel-adminpanel#269]
I am having some issues with the output of datatable. Here is how the Attribute is setup for this particular case:

`trait SchoolAttribute
{
    /**
     * @return string
     */
    public function getActionButtonsAttribute()
    {
        return '<div class="btn-group action-btn">
                    <a href="www.google.com" class="btn btn-flat btn-default">
                    <i data-toggle="tooltip" data-placement="top" title="Edit" class="fa fa-pencil"></i>
                </a></div>';

//            '<div class="btn-group action-btn">
//                 '.$this->getEditButtonAttribute('edit-school', 'admin.schools.edit').'
//                    '.$this->getViewButtonAttribute().'
//                    '.$this->getDeleteButtonAttribute('delete-school', 'admin.schools.destroy').'
//                </div>';
    }`

The controller is setup almost identical to those of Page model and Page Attribute. instead of getting a HTML view of the button in my view, I am getting a string instead, which look like this:

![image](https://user-images.githubusercontent.com/16600656/46829882-e7383400-cd53-11e8-8d9d-1089196ae6c3.png)

The inserted code is treated as sting, instead of just html.

What might have caused this?

Thanks in advance

**Comment by simoebenhida** [comment]
couldn't duplicate the bug need more informations about it please.

**Comment by hanabishirin** [comment]
> couldn't duplicate the bug need more informations about it please.

Hi, I have created a repo with the admin code for your reference, please look at the school section for detail: 

https://github.com/hanabishirin/Laravel-Adminpanel-tweak.git

I have written a seed for it as well.

Thanks,

**Comment by hanabishirin** [comment]
so I found the solution, somehow it requires an extra line for the Datatable controller when generating the buttons:
