### ISSUE TITLE
left sidebar problem

### ISSUE THREAD

**Issue by xiashiwei** [viralsolani/laravel-adminpanel#270]
Sir,there has a problem about backend left sidebar,when the contents on the right are not enough So the left side can't scroll,here's the picture
![20181013140645](https://user-images.githubusercontent.com/7830327/46902166-0620fc80-cef3-11e8-8bfb-0c1e623f50df.png)
![20181013140805](https://user-images.githubusercontent.com/7830327/46902167-0620fc80-cef3-11e8-9414-034ba63486ba.png)

**Comment by qwang135** [comment]
Can I work on this?

**Comment by xiashiwei** [comment]
> Can I work on this?

what?

**Comment by viralsolani** [comment]
@qwang135 Yes please, once issue resolved pleases give us pull request on develop branch.

**Comment by abr4xas** [comment]
Hi there @xiashiwei, I cant reproduce this. Can you tell me what is the size of your screen?

**Comment by bvipul** [comment]
@qwang135 Did you manage to solve the issue? 
And @abr4xas my screen size is 1366x768, and it happened to me too.

**Comment by abr4xas** [comment]
@bvipul ok, let me check : )

**Comment by bvipul** [comment]
@abr4xas What's the status?

**Comment by bvipul** [comment]
Adding this into our Work to do.
