### ISSUE TITLE
Add sidebarmenu backend 

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#272]
hi thanks for your project,  i am new in laravel and i want to add menu in backend and it doesnt work can you help me ?

**Comment by vrkansagara** [comment]
@lili94  I would suggest to play with demo link first and let us know where you are stuck!

**Comment by lili94** [comment]
I follow your suggest and i inderstand how work just go to menu in backend and chose backend grid type the name and it work fine
