### ISSUE TITLE
Export -component

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#277]
Hi i want to use export-component in header button blade and it doesnt work for me how can i use it please ?

**Comment by bvipul** [comment]
What is the issue that you are getting? And also please check console that you don't have any errors there.

**Comment by lili94** [comment]
Thanks for your answer I don't have any error in console  and i use this:
    buttons: [
                        { extend: 'excel', className: 'excelButton',  exportOptions: {columns: [ 0, 1, 2, 3, 4 ]  }},
                        { extend: 'pdf', className: 'pdfButton',  exportOptions: {columns: [ 0, 1, 2, 3, 4 ]  }},
                        { extend: 'print', className: 'printButton',  exportOptions: {columns: [ 0, 1, 2, 3, 4 ]  }}
                    ]
also my index.blade.php show me this i don't know why
![capture](https://user-images.githubusercontent.com/32308220/47264339-32510480-d515-11e8-9a7b-2d6ad682f3b9.PNG)

**Comment by bvipul** [comment]
You might have some typos in your js that's why your name column is not showing up. And what happens when you click on Export button?

**Comment by lili94** [comment]
Nothing happened and no issue show i spent hours and i can't fix the problem , I use this for show column
{data: 'nom', name: '{{config('module.patients.table')}}.nom'}, and the name is not showing up

**Comment by bvipul** [comment]
Have you updated the Repository for this module to include that field?

**Comment by lili94** [comment]
i updated now but i have same problem
 public function getForDataTable()
    {
        return $this->query()
            ->select([
                config('module.patients.table').'.id',
                config('module.patients.table').'.nom',
                config('module.patients.table').'.created_at',
                config('module.patients.table').'.updated_at',
            ]);
    }

**Comment by lili94** [comment]
Sorry For distributed you  but I want to ask you something when I create new module wish folder I must change for create my custom module  thanks

**Comment by lili94** [comment]
Thanks i fixed the problem of name column i wasn't declared in  resources.php and label.php 
and i still have problem with export button

**Comment by baduypaltalk** [comment]
@lili94 & @bvipul 

Did you export the image into excel file ?
I can show images to index.blade but can not export them

Can you help ?
