### ISSUE TITLE
Application key generate Issue.

### ISSUE THREAD

**Issue by gautamr777** [viralsolani/laravel-adminpanel#28]
When i clone project after composer update then after APP_KEY generate so error found some thing like this
  [RuntimeException]
  No application encryption key has been specified. ?

please tell me also issue for composer dump auto load, i found issue in window system.

**Comment by trollid** [comment]
let me pull fix for this one, and i'll open another issue about jwt

**Comment by viralsolani** [comment]
well since laravel 5.5, while running composer install, it is not creating the .env file. So before running composer install, just copy .env file from .env.example.

I've updated the readme as well.
