### ISSUE TITLE
creation new modul button export doesn't work 

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#281]
hi when i create new module export button doesn't work how can i fixi it please

**Comment by bvipul** [comment]
What is the exact issue are you facing? I could not reproduce it? Can you please explain, what is exactly not working.

**Comment by lili94** [comment]
OK thanks, when I create new module and go to this new module button action work and button export show copy, excel, print but when I click nothing happened I try everything please help

**Comment by lili94** [comment]
hi , i still have the same problem do you find solution please

**Comment by lili94** [comment]
I resolve it, missed adding these in index.blade .PHP 
Backend.DataTableSearch.init(dataTable);

thanks @bvipul

**Comment by lili94** [comment]
i resolve it, i missed adding  Backend.DataTableSearch.init(dataTable); index.blade .php

thanks@bvipul

**Comment by lili94** [comment]
i resolve it i missed add  Backend.DataTableSearch.init(dataTable); in index.blade.php
 thanks@bvipul

**Comment by lili94** [comment]
i fixed i missed add  Backend.DataTableSearch.init(dataTable); in index.blade.php

thanks @bvipul
