### ISSUE TITLE
Homepage Error

### ISSUE THREAD

**Issue by tiagosimoesdev** [viralsolani/laravel-adminpanel#283]
"Whoops, looks like something went wrong" . in homepage for demo.

**Comment by vrkansagara** [comment]
@tiagosimoesdev @tiagosimoesdev , I gone through the new installation and find that something is breaking in master branch. but we will be back soon.

**Comment by vrkansagara** [comment]
@tiagosimoesdev , The demo link is up and running fine.

**Comment by bvipul** [comment]
Thanks @vrkansagara
