### ISSUE TITLE
menu probelm

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#284]
hi when you want to change the position of menu  in backend  sidebar  is not take it  can you help me

**Comment by bvipul** [comment]
You need to change in the css for that. But we have a config file that might help you a little.
config/backend.php, try to play with 'layout' value in it.

**Comment by bvipul** [comment]
Oh sorry, I think I have fixed that issue, could you please take a new pull from our master branch. Hope your issue will be resolved.

**Comment by bvipul** [comment]
https://github.com/viralsolani/laravel-adminpanel/pull/255/commits/282a0c5bafa4d2df763445bc772f7fcff70534d6

**Comment by lili94** [comment]
Thanks so much its work
