### ISSUE TITLE
Can not run project without artisan

### ISSUE THREAD

**Issue by baduypaltalk** [viralsolani/laravel-adminpanel#287]
I can not run this project with url: localhost:88/laravel-adminpanel
Please help !

Regards,

**Comment by baduypaltalk** [comment]
How can I run this project by url: localhost/projectname  don't need execute run project with "php artisan serve" ?

Could you please me ?

**Comment by bvipul** [comment]
Hello, you need to create a virtual host to run with a url. There are plenty of docs on Google on how to do that for a laravel project. Do that, and add that new url to your .env file and you are good to go

**Comment by vrkansagara** [comment]
@baduypaltalk  You need to place the project files into server directory , lets say `/var/www/html/laravel-adminpanel`

This will provide you a external link as `http://localhost/laravel-adminpanel/public` this will work for you in most case. and if you are using apache you need to rewrite the `laravel-adminpanel` directory.

for how to rewrite you can find my [blog post over](https://vrkansagara.in/)

**Comment by baduypaltalk** [comment]
> @baduypaltalk You need to place the project files into server directory , lets say `/var/www/html/laravel-adminpanel`
> 
> This will provide you a external link as `http://localhost/laravel-adminpanel/public` this will work for you in most case. and if you are using apache you need to rewrite the `laravel-adminpanel` directory.
> 
> for how to rewrite you can find my [blog post over](https://vrkansagara.in/)

Its done, thanks bro

**Comment by baduypaltalk** [comment]
> Hello, you need to create a virtual host to run with a url. There are plenty of docs on Google on how to do that for a laravel project. Do that, and add that new url to your .env file and you are good to go

Thanks you, i've emplemented on windows os & ubuntu successfully.

**Comment by lili94** [comment]
@baduypaltalk  please can you help me to create virtual host

**Comment by baduypaltalk** [comment]
> @baduypaltalk please can you help me to create virtual host

Oh Guy,,

Hope here that you need : 

https://austin.passy.co/2012/setting-up-virtual-hosts-wordpress-multisite-with-xampp-on-windows-7/

**Comment by lili94** [comment]
hi think i use this https://github.com/worldtutorial/vhost-for-laravel/blob/master/v-host.txt and work fine
