### ISSUE TITLE
Regarding install in xampp

### ISSUE THREAD

**Issue by sahsuraj** [viralsolani/laravel-adminpanel#288]
I installed php version (PHP Version 7.1.21 )but its not able to install in my local system.

 Problem 1
   - This package requires php >=7.1.3 but your PHP version (5.6.37) does not satisfy that requirement.
 Problem 2
   - arcanedev/log-viewer 4.6.2 requires php >=7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
   - arcanedev/log-viewer 4.6.1 requires php >=7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
   - arcanedev/log-viewer 4.6.0 requires php >=7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
   - arcanedev/log-viewer 4.5.3 requires php >=7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
   - arcanedev/log-viewer 4.5.2 requires php >=7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
   - arcanedev/log-viewer 4.5.1 requires php >=7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
   - arcanedev/log-viewer 4.5.0 requires php >=7.1.3 -> your PHP version (5.6.37) does not satisfy that requirement.
   - Installation request for arcanedev/log-viewer ^4.5 -> satisfiable by arcanedev/log-viewer[4.5.0, 4.5.1, 4.5.2, 4.5
3, 4.6.0, 4.6.1, 4.6.2].

**Comment by bvipul** [comment]
Please install PHP version 7.1.3 or above as the error states clearly.
