### ISSUE TITLE
NPM problem

### ISSUE THREAD

**Issue by gautamr777** [viralsolani/laravel-adminpanel#29]
Hello,
  I have tested in windows system node js install using .exe then i run application not effect bootstrap js and fontawsome   icon apply in adminpanel.?

**Comment by viralsolani** [comment]
Please make sure you have the latest node installed. and after installing npm dependency, please run npm run development.

**Comment by bvipul** [comment]
I also have this project installed on my windows system. I have the node and npm installed. Node(6.9.4) and npm(5.5.1), it is working perfectly. Can you please check your version of node and npm. @gautamr777

**Comment by gautamr777** [comment]
ok the problem is solved 
Thanks.
