### ISSUE TITLE
Not Display Uploaded Image 

### ISSUE THREAD

**Issue by baduypaltalk** [viralsolani/laravel-adminpanel#293]
Hi Admin,

Im using Windows 7 OS,
I uploaded images from module "Setting", i took a check  and saw the image was uploaded.
But it does not display after I click update button.

Plz see the picture and my virtual domain in sourcode.

![bug](https://user-images.githubusercontent.com/8188362/47907579-20307800-debe-11e8-919c-3cb020865737.png)
![bug2](https://user-images.githubusercontent.com/8188362/47907581-20c90e80-debe-11e8-84a6-34db41008cdb.png)

I run "php artisan storage:link"  but its not display.

Plz help.

@viralsolani @bvipul @vrkansagara ...

**Comment by baduypaltalk** [comment]
Hi,
I've tried with "Blog" module and its has same error. The uploaded image does not display.
![bug3](https://user-images.githubusercontent.com/8188362/47908034-0479a180-debf-11e8-8ec5-bd560cf5ad34.png)
![bug4](https://user-images.githubusercontent.com/8188362/47908107-296e1480-debf-11e8-895e-6c3021749924.png)

plz let me know how to fix ?

**Comment by vrkansagara** [comment]
HI @baduypaltalk ,

Have you given proper permission to the directory. Does server and php can able to read the file path.

**Comment by baduypaltalk** [comment]
> HI @baduypaltalk ,
> 
> Have you given proper permission to the directory. Does server and php can able to read the file path.

Hello,

I fixed it done, i created virtual host to 'root/public' diretory.  When i copy and edit the htaccess file from 'root/public to 'root' then it OK.

Thanks for your following.

**Comment by lili94** [comment]
i didn't inderstand what you do i have the same problem can you help me please

**Comment by lili94** [comment]
@baduypaltalk please can you make capture how it s work for you i cant find solution

**Comment by baduypaltalk** [comment]
@lili94  yes of course,

- I deployed on Windows 7 OS & xampp ( php7.2x)
- I saw this isssue and these are my steps as bellow:

+ Create .htaccess in (root)\storage\app\public\  

![image](https://user-images.githubusercontent.com/8188362/49781984-38aa7280-fd47-11e8-8958-d7fc7a2bc5a3.png)

+ Implement path in view:
![image](https://user-images.githubusercontent.com/8188362/49782034-6bed0180-fd47-11e8-8a41-1a7a35a8531a.png)


- I just did it, i only use "real path" not need to run command : 'php artisan storage:link'

We can share our knowledge at future if you need, plz add my Skype account: **quocduy.itvn**

Regards @lili94

**Comment by lili94** [comment]
it doesn't work :(

**Comment by lili94** [comment]
@baduypaltalk  equipement is folder in storage folder or public folder
