### ISSUE TITLE
search box not working 

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#295]
hi when i add this to my index.blade.php  is searching just by id 
                          <th>
                                {!! Form::text('nom_patient', null, ["class" => "search-input-text form-control", "data-column" => 0, "placeholder" => trans('labels.backend.patients.table.nom_patient')]) !!}
                                    <a class="reset-data" href="javascript:void(0)"><i class="fa fa-times"></i></a>
                            </th>
i add this to the end of the page and same problem

          Backend.DataTableSearch.init(dataTable);
please help

**Comment by bvipul** [comment]
You have to provide correct data-column in the FORM::text

**Comment by lili94** [comment]
hi thanks for replay i provide correct data and everything show good in index.blade.php but the search input don't work is show me just by id

**Comment by bvipul** [comment]
The data-column attribute needs to be the column number starting from 0

**Comment by lili94** [comment]
itt 's wooorkkk thanks soo much @bvipul  for reply ,my Allah keep you always progress in your life

**Comment by bvipul** [comment]
:blush: :+1:
