### ISSUE TITLE
npm install run error

### ISSUE THREAD

**Issue by tusharsinhparmar** [viralsolani/laravel-adminpanel#297]
When i run **npm install** got error : found 4 vulnerabilities (1 low, 1 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

High            Cross-Site Scripting (XSS)
Low             Regular Expression Denial of Service
High            Missing Origin Validation
Moderate        Regular Expression Denial of Service

And not fix by **npm audit fix** command

**Comment by vrkansagara** [comment]
@tusharsinhparmar this is very specific to the node package. you are feel free to open issue [here](https://github.com/npm/npm/issues)

Is there any specific concern to the project let us know.
