### ISSUE TITLE
install.sh run error

### ISSUE THREAD

**Issue by tusharsinhparmar** [viralsolani/laravel-adminpanel#298]
While run **./install.sh** got Connected successfully! and Successfully created databasename database message with error **In SchemaException.php line 89: There is no column with name 'created_by' on table 'users'.**

**Comment by lili94** [comment]
hi try to create your database, change in env file your database name and password, then php artisan migrate and it s work fine

**Comment by vrkansagara** [comment]
@tusharsinhparmar try as per @lili94  suggestion this will resolve your problem.

**Comment by tusharsinhparmar** [comment]
Thanks @lili94 and @vrkansagara .
