### ISSUE TITLE
select Form not return id 

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#299]
hi @viralsolani  i use select in my form like this:

      <div class="col-lg-10">
           {{ Form::select('ListAllergie', $ListAllergie ,$allergie_id, ['class' => 'form-control box-size','maxlength' => 50 , 'placeholder' => ' Non définie', 'required' => 'required']) }}
        </div>
    </div>

and i pluck id in create response
              $ListAllergie =Allergie::pluck("nom_allergie","id")->toArray();

              'ListAllergie'=>$ListAllergie,
            'allergie_id'=>$this->allergie_id,

but in database id show 0 i don't know where is the problem

**Comment by vrkansagara** [comment]
This is very common problem you can google for it! @lili94

**Comment by lili94** [comment]
hi yes i fix it yesterday like this 
 <div class ="form-group">
        {{ Form::label('list_patient', trans('validation.attributes.backend.consultations.nom_patient'), ['class' => 'col-lg-2 control-label required']) }}
        <div class="col-lg-10">
        <select id="patient_id" name="patient_id" class="form-control select2 box-size" required="required" placeholder=" Non définie" >
        <option value="">Non définie</option>
            @foreach($listPatient as $key)
            
                <option value ="{{$key->id}}">{{$key->nom_patient}} {{$key->prenom_patient}}</option>
            @endforeach
            </select>
        </div>
   </div>   
thanks

**Comment by baduypaltalk** [comment]
@lili94 
Did you implement the ajax event like this ?

![image](https://user-images.githubusercontent.com/8188362/49841238-719b2380-fde9-11e8-8185-509cd3e62f1d.png)

I would like show all employees depend Department when i select a department.

If yes, im so happy if you take some your source capture about it. 

Thanks

**Comment by lili94** [comment]
@baduypaltalk  yes of course i do it without ajax just add foreign key of your module in database then go to create response in my code 
![capture1](https://user-images.githubusercontent.com/32308220/49855573-f9832c80-fded-11e8-9124-820270b78cdd.PNG)
![capture2](https://user-images.githubusercontent.com/32308220/49855574-fa1bc300-fded-11e8-8ca2-2b772d8a44bd.PNG)
![capture3](https://user-images.githubusercontent.com/32308220/49855575-fa1bc300-fded-11e8-90cf-e12b739fd59e.PNG)
![capture4](https://user-images.githubusercontent.com/32308220/49855576-fa1bc300-fded-11e8-9fd8-15496f5a0be8.PNG)
and in view this
![capture5](https://user-images.githubusercontent.com/32308220/49855577-fab45980-fded-11e8-96e4-d181c535e9ad.PNG)

**Comment by baduypaltalk** [comment]
@lili94  

i think your source does noy match with my question,

When i 'onchange' Department selectbox:

![image](https://user-images.githubusercontent.com/8188362/49857663-b6dd4680-fe25-11e8-8a64-a634c294dfde.png)

Employees selectbox shows only employees itsself.

![image](https://user-images.githubusercontent.com/8188362/49857839-0e7bb200-fe26-11e8-958d-91bace8485ab.png)

I've just done it.
I still use ajax and now im so happy  =))

![image](https://user-images.githubusercontent.com/8188362/49857951-513d8a00-fe26-11e8-9056-e5f65f1ead6e.png)
