### ISSUE TITLE
How to show  foreign key in index blade

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#301]
hi @viralsolani  i have foreign key in my table to show name in create blade and it s work fine but in index it show me just the id i don't know how can i fix it 
![k](https://user-images.githubusercontent.com/32308220/48894250-8c115b00-ee42-11e8-9f51-ffc4ea6703f1.PNG)

nom patient is refernce to table patient

**Comment by bvipul** [comment]
Please check, blog module for reference on this

**Comment by lili94** [comment]
hi thanks for your fast answer ,but you didn't anderstand me i want to show  foreign key  name   in server side datatable

**Comment by bvipul** [comment]
Hello, if you look at the blog implementation, you will see that, we have a created_by foreign key and in the datatable we are showing the name of the user from that foreign key.

**Comment by viralsolani** [comment]
Yes @lili94  you can check user module and blog module for the reference. closing the ticket as of now.

**Comment by lili94** [comment]
hi @viralsolani and @bvipul  thanks i try and i do like you telle me but i got error in my join  vaccination repository 
![01](https://user-images.githubusercontent.com/32308220/49209971-31d14680-f3bc-11e8-920f-34a69a842830.PNG)
![02](https://user-images.githubusercontent.com/32308220/49209973-3269dd00-f3bc-11e8-805c-f5ff42a0ceba.PNG)
![03](https://user-images.githubusercontent.com/32308220/49209974-3269dd00-f3bc-11e8-847e-d8e17911c4ff.PNG)
![04](https://user-images.githubusercontent.com/32308220/49209975-3269dd00-f3bc-11e8-9042-a2d15ef92c38.PNG)
![05](https://user-images.githubusercontent.com/32308220/49209977-3269dd00-f3bc-11e8-8790-45fd7878f33b.PNG)
![06](https://user-images.githubusercontent.com/32308220/49209978-33027380-f3bc-11e8-9bc8-f3021b8059ea.PNG)

and i got this error i try everything please help
![07](https://user-images.githubusercontent.com/32308220/49210086-73fa8800-f3bc-11e8-989f-1ae51fc89702.PNG)
