### ISSUE TITLE
Self Relation - Parent & child in the same table not work

### ISSUE THREAD

**Issue by baduypaltalk** [viralsolani/laravel-adminpanel#303]
Hi,

I would like to build a Create View for 'Company' module, which has a 'selectbox' sames as the 'BlogModule.Category'.

![blog-create-module](https://user-images.githubusercontent.com/8188362/49056746-8bf0d100-f22f-11e8-852d-ccd3e5e459e0.png)

My steps:
- Generate module 'Company' include: CRUD
- Change Create View  
-  Run Company.Create ( it displays the error )

Please see the attached images: table database ( focus the relation of fields id - parent_id) and other attached images .
And tell me how to build the  this select box for "Parent Id" field.

Many thanks.

![create_controller](https://user-images.githubusercontent.com/8188362/49056840-e68a2d00-f22f-11e8-9d42-b877f06cf3bf.png)
![create_response](https://user-images.githubusercontent.com/8188362/49056841-e68a2d00-f22f-11e8-91f0-5f17f80c7dd2.png)
![edit_response](https://user-images.githubusercontent.com/8188362/49056842-e68a2d00-f22f-11e8-9d36-4f14c7e45bc7.png)

Blade view:

![form-blade](https://user-images.githubusercontent.com/8188362/49056843-e722c380-f22f-11e8-9ab4-14eba0d3a893.png)
![model_company_relation](https://user-images.githubusercontent.com/8188362/49056844-e722c380-f22f-11e8-907f-6e2b90e5b799.png)
![model-company](https://user-images.githubusercontent.com/8188362/49056845-e722c380-f22f-11e8-8ec6-293de9d3b05c.png)
![table_companies](https://user-images.githubusercontent.com/8188362/49056846-e7bb5a00-f22f-11e8-986f-f1661da2535a.png)

**Comment by bvipul** [comment]
In CreateResponse, I don't see if you have passed the array of companies, just like we have passed tags and categories to the CreateResponse

**Comment by bvipul** [comment]
Look at BlogsController for more reference, if still its not resolved, if you have the project on github, please send me the link, I will try to solve it in your repo.

**Comment by baduypaltalk** [comment]
@bvipul  thanks you.

I've implemented it done.
