### ISSUE TITLE
Active button in index.blade

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#304]
hi @viralsolani  i need your help sorry to bother you i am doing somthing like button active  and everthing work well  
![capture11](https://user-images.githubusercontent.com/32308220/49080015-8cdf2e00-f242-11e8-81db-fdee53dce6d6.PNG)
![capture22](https://user-images.githubusercontent.com/32308220/49080017-8cdf2e00-f242-11e8-9e68-ba8517ed917e.PNG)
but like yous see i can't get like you i got 0 and 1
![capture33](https://user-images.githubusercontent.com/32308220/49080087-cd3eac00-f242-11e8-9626-2d64085e4a05.PNG)

i use  this 
public function getStatusLabelAttribute()
    {
        if ($this->isActive()) {
            return "<label class='label label-success'>".trans('labels.general.active').'</label>';
        }

        return "<label class='label label-danger'>".trans('labels.general.inactive').'</label>';
    }

    /**
     * @return bool
     */
    public function isActive()
    {
        return $this->status == 1;
    }
}
but i don't know what i miss how can i use it in my model i put is active in rosource too pleaase help i try everything

**Comment by cygnet-bvipul** [comment]
Hello @lili94, use 
`->addColumn('status', function ($model) {
                return $model->status_label;
            })` 
in your TableController

**Comment by bvipul** [comment]
Hello @lili94, use
->addColumn('status', function ($model) { return $model->status_label; })
in your TableController

**Comment by lili94** [comment]
oohh thankss @viralsolani  it s' work
