### ISSUE TITLE
Self Relation - Show Parent Name on Index View 

### ISSUE THREAD

**Issue by baduypaltalk** [viralsolani/laravel-adminpanel#306]
Hi,

Please see my attached images.

I would like to show the  'name'  maping with the parent_id in the same table on self-relation.
Can you tell me how to do that ?

Thanks
![screenshot-iweb me-2018 11 29-09-32-46](https://user-images.githubusercontent.com/8188362/49195594-4dd3e880-f3ba-11e8-84a2-3a523232249d.png)
![untitled](https://user-images.githubusercontent.com/8188362/49195595-4dd3e880-f3ba-11e8-9a2c-603e90af3aa3.png)

**Comment by lili94** [comment]
i have the same issue i try follow blogcategorie like what he was done with createdby but i have datatable error in join

**Comment by lili94** [comment]
do you resolve it @baduypaltalk

**Comment by baduypaltalk** [comment]
> do you resolve it @baduypaltalk

:)  It does not resolve Lili.  Im still waiting for the answer from  @bvipul  handsomes  :)

**Comment by bvipul** [comment]
Hello @baduypaltalk, I think, you need to add a join in Repository with the same table and make an alias to it and then use that alias to get the name that you desire.

If you still find it difficult, then please add comment with the repository getForDatatable() method.

**Comment by lili94** [comment]
@baduypaltalk  @bvipul  i resolve it you must add like @bvipul said in controller table your foreign key , then in resource  like page module add also the relationship of module in resource after that in your repository add the join then in view and it s work follow created_by in page module

**Comment by baduypaltalk** [comment]
> Hello @baduypaltalk, I think, you need to add a join in Repository with the same table and make an alias to it and then use that alias to get the name that you desire.
> 
> If you still find it difficult, then please add comment with the repository getForDatatable() method.

OK, im trying .... Thanks you

**Comment by baduypaltalk** [comment]
> @baduypaltalk @bvipul i resolve it you must add like @bvipul said in controller table your foreign key , then in resource like page module add also the relationship of module in resource after that in your repository add the join then in view and it s work follow created_by in page module

@lili94 could you take some captures about your source here ?

**Comment by lili94** [comment]
yes of course form me is (id_patient) foriegn  key of table patient want to show it in table consultation 

1-consultation table
![capture01](https://user-images.githubusercontent.com/32308220/49716336-be4cf600-fc53-11e8-96de-c5ec98a6d2f1.PNG)
2-consultation tablecontroller
![capture02](https://user-images.githubusercontent.com/32308220/49716363-cefd6c00-fc53-11e8-8504-6abd41fb6fcd.PNG)
3-consultation resource
![capture03](https://user-images.githubusercontent.com/32308220/49716379-dd4b8800-fc53-11e8-9937-48bc2292f3af.PNG)
4-consultaion response
![capture04](https://user-images.githubusercontent.com/32308220/49716402-f6543900-fc53-11e8-980d-fa31dbf56d0b.PNG)
5-consultation repository
![capture05](https://user-images.githubusercontent.com/32308220/49716463-20a5f680-fc54-11e8-
98c8-dc8c72d97760.PNG)
6-7 index.blade
![capture06](https://user-images.githubusercontent.com/32308220/49716488-35828a00-fc54-11e8-9606-df0768b3d88d.PNG)
![capture07](https://user-images.githubusercontent.com/32308220/49716489-35828a00-fc54-11e8-8ab7-158848846f2d.PNG)
8-consultaionrelationship
![capture08](https://user-images.githubusercontent.com/32308220/49716602-809c9d00-fc54-11e8-8282-fa544f04dec3.PNG)
 i hope it s work ;)

**Comment by baduypaltalk** [comment]
Ok its done,

Thanks
