### ISSUE TITLE
After login always sends me to Dashboard

### ISSUE THREAD

**Issue by nidhishankermodi** [viralsolani/laravel-adminpanel#307]
All roles must have redirections. According to their role redirections, we can send them to a particular path.

Right now, all user logins are sending me to Dashboard whereas seems dashboard permissions are not given to the particular user.

We are using the same approach in our of our project.

![image](https://user-images.githubusercontent.com/15975325/49201382-b4f79a00-f3c6-11e8-95e8-c65c0049f53c.png)

**Comment by viralsolani** [comment]
Yes for that you need to do customization and after login needs to check role and accordingly send to different places or dashboard. you can check the example of admin and frontend user.
