### ISSUE TITLE
permission for new module

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#308]
hi @viralsolani @bvipul  i have module patients is work fine i create new role **medcin** i seed pesmision module patient in permission table seeder.php i create new user and associte role medcin with permission module patient view-create-edit-delete when i login with this new user i got nothing please help

 thanks

**Comment by lili94** [comment]
please @viralsolani  i need your help

**Comment by navdeep1186** [comment]
is there any success!

I am also getting the same error when I created a new module and assign to execute user.
it has not displayed that module when execute user logged in.

**Comment by viralsolani** [comment]
@lili94 you got nothing means? can you please explain your issue? You need to add permission in to form request classes and in the sidebar as well.

**Comment by lili94** [comment]
thanks @viralsolani  it s work i was worng in url  @navdeep1186  look add permision in your request exemple view-patient then change in your controller module using the same request not formeRequest then add permission in 
MenuTableSeeder  PermissionTableSeeder ModuleTableSeeder finally sidebar.blade.php and it s wooork

**Comment by navdeep1186** [comment]
hi @viralsolani @bvipul 
will you tell me how I increase the sessoin time out? because after few minutes it is signout by default
