### ISSUE TITLE
Login in Demo

### ISSUE THREAD

**Issue by GrCOTE7** [viralsolani/laravel-adminpanel#309]
Hi,

I tried to connect in the Demo with admin@admin.com & 1234 as PW...
(Seen in the seeder...)

But it doesn't work :-(...

Thanks to verify that

**Comment by bvipul** [comment]
Hello @GrCOTE7, sorry for that, I think the password is changed. @vrkansagara can you please look into that? Thanks.

**Comment by GrCOTE7** [comment]
Note: In my local deployment,  admin@admin.com/1234 works... ;-)

**Comment by vrkansagara** [comment]
@GrCOTE7 Yes, this is the default password. And a matter of demo link  that any body can able to change the password from the admin panel @bvipul  so I am sure that I didn't do it. 

But let me reset whole database so people can able to login again.

Also we have to implement such feature using .env file that only available variable can able to change the password of supper user only . 

/cc @viralsolani @bvipul 

This feature prevent user to change a password from admin panel for only supper admin use only.

**Comment by vrkansagara** [comment]
re-open for confirmation with user(s).

**Comment by bvipul** [comment]
Thanks @vrkansagara

**Comment by vrkansagara** [comment]
@GrCOTE7  and @bvipul  this might resolved for the issuer.
