### ISSUE TITLE
[JWT] Laravel 5.5 use JWT dev

### ISSUE THREAD

**Issue by trollid** [viralsolani/laravel-adminpanel#31]
error when
`php artisan jwt:generate`

Error : 
```
[ReflectionException]
Method Tymon\JWTAuth\Commands\JWTGenerateCommand::handle() does not exist
```

please refer to new JWT for laravel 5.5

worth to take a look : 
http://laravelcode.com/post/method-tymonjwtauthcommandsjwtgeneratecommandhandle-does-not-exist
https://github.com/tymondesigns/jwt-auth/issues/1298

**Comment by viralsolani** [comment]
Thanks for resolving this issue.
