### ISSUE TITLE
question about package

### ISSUE THREAD

**Issue by darvishiyan-mahdi** [viralsolani/laravel-adminpanel#310]
hi i like to know what acl method do you use in your package is it built in laravel guard or something else

**Comment by bvipul** [comment]
Hello @darvishiyan-mahdi, we are using simple permissions in db and checking those using Access Helper and we have helper methods to check if the permission is given to that particular user. It is having role wise permissions as well as user wise permissions. And User permissions override the role permissions.

**Comment by viralsolani** [comment]
@darvishiyan-mahdi , if you have a question related to ACL, please do let us know. we will sure let you know about it. for now, I am closing this ticket.
