### ISSUE TITLE
we hav an error after install project.

### ISSUE THREAD

**Issue by tarzanpasha** [viralsolani/laravel-adminpanel#311]
"The Mix manifest does not exist. (View: /home/vagrant/code/laravel-adminpanel/resources/views/frontend/layouts/app.blade.php) (View: /home/vagrant/code/laravel-adminpanel/resources/views/frontend/layouts/app.blade.php) ◀"

that error appears after we try to load a project page

**Comment by bvipul** [comment]
This is because you haven't done `npm run dev`

**Comment by tarzanpasha** [comment]
thank you! i hav just do it and all works. and I came to delete my comment and see that you have already answered!!!
I'm so ssory

**Comment by bvipul** [comment]
No issues, have a blast..:sunglasses:
