### ISSUE TITLE
Is this compatible with MS SQL?

### ISSUE THREAD

**Issue by Tranest8tion** [viralsolani/laravel-adminpanel#314]
As I am beginning to to use this, I keep seeing mySQL errors. Is this not compatible with MS SQL? In User Management, I get this error:

![screen shot 2018-12-11 at 1 52 10 pm](https://user-images.githubusercontent.com/13798489/49822793-1cf59b00-fd4c-11e8-9d8f-aaa5f64860b6.png)

Any and all assistance is greatly appreciated.

Thank you!

**Comment by bvipul** [comment]
If laravel supports then, this project does it too. But at some places we have used raw queries which are based on mysql, so you might need to change them.

**Comment by viralsolani** [comment]
@Tranest8tion as of now we will support MySQL only.  So closing this issue.
