### ISSUE TITLE
Redirect in Route

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#315]
hi @viralsolani @bvipul  i want to make the project enter in login page and dashboard i d'ont want  to redirect to frontend  can you help me please i want to use login account an dashboard

**Comment by baduypaltalk** [comment]
@lili94 
if you need only set default page with Login, you can try:
- goto FrontendController@index function and implement as this code:

![image](https://user-images.githubusercontent.com/8188362/49920329-5fe67880-fedc-11e8-88b9-5395084908ff.png)

Hope it work!

**Comment by lili94** [comment]
yes it work i fixit yesterday thanks for you  help

**Comment by lili94** [comment]
@baduypaltalk @bvipul @viralsolani i want to delete this and redirect to login page
![capture22](https://user-images.githubusercontent.com/32308220/49931526-530b5a00-fec7-11e8-8845-00cad99bd5e0.PNG)
