### ISSUE TITLE
History , history Types

### ISSUE THREAD

**Issue by baduypaltalk** [viralsolani/laravel-adminpanel#316]
I would like to make the history of generated modules.

Now i can see only the history of defaul modules: blog, blog category, access user, access role, access permission.

Plz help me 
@viralsolani  @bvipul  & all

**Comment by bvipul** [comment]
@baduypaltalk You need to add history types for those and emit events when certain things happens and catch those events and listen for them in listeners and use the history() helper method to save the history. You can take reference from listeners for other modules.

**Comment by viralsolani** [comment]
@baduypaltalk Yes, you can see the example of any default module and replicate the feature in your new modules. please let us know if you have any other question related to history. Closing this ticket for now.
