### ISSUE TITLE
Add new Admin dashboard panel

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#317]
hi @viralsolani @bvipul and all i want to change design of backend admin i change login form and i want to change backend but js and css don't wont to work he work fine in login i add assets to public folder but d'ont wont to work

**Comment by viralsolani** [comment]
@lili94 we are using admin LTE for Laravel Admin Panel. if you want to change the design , you can create your custom CSS and override the admin lte CSS rules.

**Comment by lili94** [comment]
hi @viralsolani  i create my custom css but i d'ont know where can i override the admine lte css rules please help
