### ISSUE TITLE
Error: Swift_TransportException (530)

### ISSUE THREAD

**Issue by jobferrera** [viralsolani/laravel-adminpanel#324]
Swift_TransportException (530)
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required "

**Comment by sirfarmalot** [comment]
+1 how to get registration to work correctly?

**Comment by viralsolani** [comment]
well, you guys need to add SMTP configuration in your .env files.

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

**Comment by bangtiray** [comment]
in file .env you can set like : 
MAIL_DRIVER=smtp
MAIL_HOST=mail.domain.com
MAIL_PORT=465
MAIL_FROM=donotreply@email.com
MAIL_FROM_NAME=Admin
MAIL_USERNAME=noreply@email.com
MAIL_PASSWORD=*******
MAIL_ENCRYPTION=ssl

**Comment by bvipul** [comment]
The answer from @bangtiray and @viralsolani should solve your issue.
