### ISSUE TITLE
Error: Cannot find module laravel-adminpanel\node_modules\laravel-mix\setup\webpack.config.js'  

### ISSUE THREAD

**Issue by suresh5** [viralsolani/laravel-adminpanel#325]

**Comment by viralsolani** [comment]
@suresh5 can you please give us some screenshots?  are you able to run npm run dev sucessfully ?

**Comment by lili94** [comment]
hi @suresh5  you miss npm install , after that npm run development try that

**Comment by suresh5** [comment]
> hi @suresh5 you miss `npm install` , after that `npm run development` try that

i did like that only bro

**Comment by bvipul** [comment]
@suresh5 what is the error you are encountering while doing `npm install`, because surely there is some error in that.

**Comment by viralsolani** [comment]
@suresh5 Please double check if you have any error while doing `npm install `or `npm run dev.` And let us know if this issue persists.

**Comment by satyamraz** [comment]
Error when running run server in webpackconfig
