### ISSUE TITLE
Combine Two Columns From DataTable

### ISSUE THREAD

**Issue by lili94** [viralsolani/laravel-adminpanel#326]
hi @viralsolani @bvipul I want to combine two columns in my DataTable. I have name and surname but I want to combine them and show just one column with the full name.
Blade

```
<th>{{ trans('labels.backend.patients.table.id') }}</th>
<th>{{ trans('labels.backend.patients.table.nom_patient') }}</th>
<th>{{ trans('labels.backend.patients.table.prenom_patient') }}</th>
<th>{{ trans('labels.backend.patients.table.date_naissance') }}</th>
```
DataTable Ajax

```
columns: [ {data: 'id', name: '{{config('module.patients.table')}}.id'},
    {data: 'nom_patient', name: '{{config('module.patients.table')}}.nom_patient'},
    {data: 'prenom_patient', name: '{{config('module.patients.table')}}.prenom_patient'},


```
![screenshot_2019-01-07 gestion des patients](https://user-images.githubusercontent.com/32308220/50799570-da889500-12dc-11e9-933a-16b3f1c7f060.png)

**Comment by ghantalavishal** [comment]
you can combine two colom into one using _invoke method which is in TableController file. keep one colom in blade and combine name and surname into one using invoke method with help of addColumn function.

**Comment by lili94** [comment]
hi @ghantalavishal please can you show me how i c'ant make it

**Comment by ghantalavishal** [comment]
@lili94  can you provide me your tableController file OR _invoke method code, I will explain you how to do.

**Comment by lili94** [comment]
HI @ghantalavishal  sorry to be so late and thanks for your help this is my invoke function    

```
 public function __invoke(ManagePatientRequest $request)
    {
        return Datatables::of($this->patient->getForDataTable())
            ->escapeColumns(['id'])
            ->addColumn('nom_patient', function ($patient) {
                return $patient->nom_patient;
            })
            ->addColumn('prenom_patient', function ($patient) {
                return $patient->prenom_patient;
            })
```

**Comment by ghantalavishal** [comment]
Hello @lili94 

Try this way 

```
public function __invoke(ManagePatientRequest $request)
    {
        return Datatables::of($this->patient->getForDataTable())
            ->escapeColumns(['id'])
            ->addColumn('nom_patient', function ($patient) {
                return $patient->nom_patient.''.$patient->prenom_patient;
            })
```

I just removed "prenom_patient" column and combine into one, now you need to remove "prenom_patient" line accordingly from DataTable Ajax call and Blade template.

Let me know your reply...

**Comment by lili94** [comment]
hi thaaanks so much it s workk , thanks for your help
