### ISSUE TITLE
set max file size

### ISSUE THREAD

**Issue by bangtiray** [viralsolani/laravel-adminpanel#327]
Hi Viral.
how to set a file max size in config-> lfm.php where files are more than 10mb
thanks viral

**Comment by lili94** [comment]
hi @bangtiray go to config/lfm.php and change this tow line 
 'max_image_size' => 50000,
 'max_file_size'  => 50000,
to 
 'max_image_size' => 100000,
 'max_file_size'  =>100000,
try that

**Comment by bangtiray** [comment]
thank @lili94 
i will try it

**Comment by viralsolani** [comment]
@bangtiray I hope this issues has been resolved. Closing this ticket for now.
