### ISSUE TITLE
view permission is not creating

### ISSUE THREAD

**Issue by HaroonAhmad17** [viralsolani/laravel-adminpanel#329]
how we can create view permission while generating curd?
![viewissue](https://user-images.githubusercontent.com/34153693/51099383-1eeec600-17f2-11e9-8dc1-022365c77af3.PNG)

**Comment by bvipul** [comment]
View permissions are always created as you generate the crud. Can you please explain, in which case did this view permission did not get created? Maybe the name will be different in DB and in the request. If so, then please report that, because that might be a generator issue.

**Comment by viralsolani** [comment]
@HaroonAhmad17 Any update ?
