### ISSUE TITLE
Accessing model in edit controller action

### ISSUE THREAD

**Issue by invaders-xx** [viralsolani/laravel-adminpanel#330]
Dear all,

First of all, I would like to thank you and congratulate for this great projet which helps me a lot to get deeper into Laravel.

I am a Laravel's newbie and I am facing an issue:

I have this route definition:
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    
    Route::group( ['namespace' => 'Process\Group','prefix' => 'processes', 'as' => 'processes.'], function () {
        Route::model('groups', 'App\Models\Process\Group\ProcessGroup');
        Route::get('{process}/groups', 'ProcessGroupsController@index')->name('groups.index');
        Route::get('{process}/groups/create', 'ProcessGroupsController@create')->name('groups.create');
        Route::resource('groups', 'ProcessGroupsController')->except(['index','create']);
        //For Datatable
        Route::post('{process}/groups/get', 'ProcessGroupsTableController')->name('groups.get');
    });
    
});

I have this controller edit action:

    /**
     * Show the form for editing the specified resource.
     *
     * @param  ProcessGroup  $processgroup
     * @param  EditProcessGroupRequest  $request
     * @return \App\Http\Responses\Backend\Process\Group\EditResponse
     */
    public function edit(ProcessGroup $processgroup, EditProcessGroupRequest $request)
    {
        return new EditResponse($processgroup);
    }

But when I edit, I have no data in the $processgroup object. When I look at the logs, no query to the database is done.

I have a similar definition for another model and it's working well:
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'admin'], function () {
    
    Route::group( ['namespace' => 'Process'], function () {
        Route::resource('processes', 'ProcessesController', ['except' => []]);
        //For Datatable
        Route::post('processes/get', 'ProcessesTableController')->name('processes.get');
    });
    
});

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Process  $process
©     * @return \App\Http\Responses\Backend\Process\EditResponse
     */
    public function edit(Process $process, EditProcessRequest $request)
    {
        $domains = Domain::getSelectData();
        return new EditResponse($process,$domains);
    }

Can you please help me in solving this issue?

**Comment by bvipul** [comment]
The name of the variable in your edit method is incorrect, I guess the variable name should be $group in edit method definition

**Comment by ivantree** [comment]
@invaders-xx I have the same issue, but I can't fix it.

**Comment by bvipul** [comment]
@ivantree check this out: https://laravel.com/docs/5.7/routing#explicit-binding
