### ISSUE TITLE
role_must_contain_permission not working

### ISSUE THREAD

**Issue by invaders-xx** [viralsolani/laravel-adminpanel#332]
Hi,
I set in config.access
'roles' => [
        /*
         * Whether a role must contain a permission or can be used standalone as a label
         */
        'role_must_contain_permission' => false,
    ],

But when I try to create a role I still have the message:
"You must select at least one permission for this role."
Many thanks for your feedback.

**Comment by invaders-xx** [comment]
I found the issue : it comes from StoreRoleRequest

**Comment by invaders-xx** [comment]
Class should be :
namespace App\Http\Requests\Backend\Access\Role;

use App\Http\Requests\Request;

/**
 * Class StoreRoleRequest.
 */
class StoreRoleRequest extends Request
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return access()->allow('create-role');
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $permissions = '';

        if (config('access.roles.role_must_contain_permission') && $this->associated_permissions != 'all') {
            $permissions = 'required';
        }

        return [
            'name'          => 'required|max:191',
            'permissions'   => $permissions,
        ];
    }

    public function messages()
    {
        return [
            'permissions.required' => trans('exceptions.backend.access.roles.needs_permission'),
        ];
    }
}

The issue is the same fro UpdateRoleRequest

**Comment by viralsolani** [comment]
Yes, we put validation for it. if you don't want you can modify according to your needs.
