### ISSUE TITLE
viralsolani/laravel-adminpanel

### ISSUE THREAD

**Issue by Aleintel** [viralsolani/laravel-adminpanel#335]
Hello,

for the "viralsolani / laravel-adminpanel" project, I would like to know where the information is stored. Is there a Database?

Thanks a lot.

Alessandro

**Comment by pratik916** [comment]
Yes Alessandro, there is obviously database to store information. You just
need to provide configuration of database at the time of installation.

**Comment by viralsolani** [comment]
@Aleintel As of now, we are only supporting MySQL for Laravel Admin Panel.
