### ISSUE TITLE
font osem icon not showing

### ISSUE THREAD

**Issue by arnavdots** [viralsolani/laravel-adminpanel#336]
font osem icon not showing

**Comment by viralsolani** [comment]
@arnavdots please share some screenshot.

**Comment by bvipul** [comment]
probably some CORS issue.

**Comment by vrkansagara** [comment]
@arnavdots  Can you share more details on this issue ? So our contributor know more on the same !

**Comment by Habibmd007** [comment]
![capture](https://user-images.githubusercontent.com/19504720/52401315-93640e80-2aeb-11e9-896f-5ab3f59068e4.PNG)
fontawesome is not working

**Comment by bvipul** [comment]
Your APP_URL in .env is wrong

**Comment by tickleTest** [comment]
same with me
![image](https://user-images.githubusercontent.com/47444092/52468942-1e650780-2bc5-11e9-9e53-8cbb245854c5.png)

**Comment by bvipul** [comment]
> Your APP_URL in .env is wrong

**Comment by viralsolani** [comment]
I hope you got the answer. Please let us know if the issue persists.

**Comment by jjmontalban** [comment]
What value must be in APP_URL in .env?

I tried with:

APP_URL=http://localhost

APP_URL=http://localhost/nameapp

and

APP_URL=http://localhost/nameapp/public


My app is in localhost/nameapp/public

Css works but icons not showed like @tickleTest

**Comment by boedyirh** [comment]
Experience the same error
