### ISSUE TITLE
No templates defined.

### ISSUE THREAD

**Issue by Aleintel** [viralsolani/laravel-adminpanel#338]
Hello,
in "Edit Page" - Insert - Template I see the following error: "No templates defined."

How can I load a default template and make it static?

Thanks for the answer,

Alessandro

**Comment by Aleintel** [comment]
How can i put a standard template? can you help me?

**Comment by bvipul** [comment]
https://www.tiny.cloud/docs/plugins/template/

**Comment by viralsolani** [comment]
I think this will help. closing this issue for now.
