### ISSUE TITLE
Datatable error when user session ends

### ISSUE THREAD

**Issue by invaders-xx** [viralsolani/laravel-adminpanel#341]
Hi,

If the session is expired, I get an error when on a datatable page. Can you please give me some inputs to handle redirection to login while datatable ajax reload failed due to session expired ?

Many thanks in advance.

**Comment by bvipul** [comment]
Maybe try this: https://viralpatel.net/blogs/jquery-ajax-handling-unauthenticated-request-ajax/

See if it helps.
Basically what it does is, gives you a method that handles all ajaxErrors and does a page reload on 403. So if the page reloads, our middleware will work and will redirect to login page.

**Comment by invaders-xx** [comment]
Thanks your answer, I will give it a try.
