### ISSUE TITLE
$request in Custom Middleware returns empty

### ISSUE THREAD

**Issue by sohailglt** [viralsolani/laravel-adminpanel#342]
This middleware works properly on local server but not on the live server.

`public function handle($request, Closure $next)
    {
        return $this->validate($request,$next);
    }
 private function validate($request,$next)
    {
        $access_key = $request->get('api_key');
        echo $access_key;
        exit();`

**Comment by bvipul** [comment]
@viralsolani @vrkansagara can you please check this?

**Comment by vrkansagara** [comment]
Sure. Let me see and update the same.

**Comment by viralsolani** [comment]
I've checked and it works well. Can you please give us error info or screenshot?

**Comment by sohailglt** [comment]
/api/v1/fetch?api_key=xyz

`Route::group(['namespace' => 'Api\V1', 'prefix' => 'v1', 'as' => 'v1.'], function () {
    Route::middleware(['accessKeyValidator'])->group(function () {
        Route::get('fetch', 'ApiDetailsController@fetchdetails');
    });
});`

`    class AccessKeyValidator
{
public function handle($request, Closure $next)
    {
        return $this->validate($request,$next);
    }

    public function validate($request,$next)
    {
        $access_key = $request->get('api_key');
        echo $access_key;
    }
}`

Here is the complete scenario, I want to get API key from URL in middleware, but returns nothing
