### ISSUE TITLE
Module created by Module Generator

### ISSUE THREAD

**Issue by tickleTest** [viralsolani/laravel-adminpanel#344]
The index page of the module works fine, but when i click edit button..it displays an error. How to fix this
![image](https://user-images.githubusercontent.com/47444092/52468786-b0204500-2bc4-11e9-9d9a-ec66e608895b.png)

**Comment by bvipul** [comment]
Look in the edit method in the controller to check if that variable name 'amenity' is actually sent to the blade file

**Comment by tickleTest** [comment]
found it, thanks
