### ISSUE TITLE
Issue while adding custom URL in Menu

### ISSUE THREAD

**Issue by sohailglt** [viralsolani/laravel-adminpanel#346]
![screenshot from 2019-02-12 20-21-31](https://user-images.githubusercontent.com/5951985/52646068-e67efc80-2f03-11e9-90a5-67675d1ee0bd.png)
I am facing issue while adding custom URL in menu, WIll you please let me know how to fix this issue.?

**Comment by vrkansagara** [comment]
@sohailglt , I have tested on demo link but I didn't found any such issue . Kindly provide steps to reproduce it. 

I have tested on this  [ demo link at  ] (https://apiway.in/admin/menus/1/edit) and it's working perfect.
