### ISSUE TITLE
SQLITE

### ISSUE THREAD

**Issue by Fosphatic** [viralsolani/laravel-adminpanel#348]
Hey there,

is it possible to integrate into installer the possibility to choose sqlite instead of sql driver? It would be just awesome.

Regards,

Fossy

**Comment by bvipul** [comment]
we had sqlite before, but it is somehow breaking our test cases. But it should work fine. I am not sure but you can check the install script, it will have commented lines for including sqlite.

**Comment by Fosphatic** [comment]
Yeah it does run, except the modules entry in the menu. It throws following: 

DataTables warning: table id=modules-table - Exception Message:

SQLSTATE[HY000]: General error: 1 no such column: .name (SQL: select "modules"."id", "modules"."name", "modules"."url", "modules"."view_permission_id", "modules"."created_by", "modules"."updated_by", "users"."first_name" as "created_by" from "modules" left join "users" on "users"."id" = "modules"."created_by" order by ""."name" asc limit 10 offset 0)

Well it was mentioned as feature request at all. It's not a problem to switch it manually to sqlite database, but the php artisan install:app isn't working so just skip this step is the only option.

Thank you anyway it looks like a nice solution for small projects. <3

**Comment by vrkansagara** [comment]
@Fosphatic  I have also tested sqlite for the same but found same error which you are facing earlier. But if you still want to use sqlite than you have to configure database configuration manually, than and than it will work!

**Comment by Fosphatic** [comment]
@vrkansagara yeah it is working except the one error as wrote before. Thanks!
