### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by bvipul** [viralsolani/laravel-adminpanel#349]

**Comment by vrkansagara** [comment]
Hello @bvipul  This issue arise because of module generator , if you crate any random module using white space so it break laravel basic flow for web routing and controller and migration as well so we need to really take care of it while we give an UI for such operation !

**Comment by vrkansagara** [comment]
Also I found another issue for this message "Note : You need to have 0777 permission to all folders of the project." As this is not a security best practise from server side.

**Comment by bvipul** [comment]
Yes we need to take care of this issue.

But for the permission note, it doesn't matter if the permission is required to be 777, as modules are supposed to be created only in development environment, and then make changes and then deploy to your server. So, the permission one is not an issue.

**Comment by bvipul** [comment]
Although the space in name needs to be rectified, by camel case name or something like that. Suggestions are appreciated.

**Comment by vrkansagara** [comment]
@bvipul  I am facing this issue of demo link because once space is inserted by module creator it break the application  flow as per expected result so , We are getting multiple  open issue for demo link.

**Comment by bvipul** [comment]
Okay, I will look into the package for the issue. Will release a version soon

**Comment by vedbhawsar** [comment]
@bvipul there is one more issue I noticed in module generator. When it creates the module, in view file the **reference object is in singular** but from the EditResponse.php file its pass as the plural name. 

### **from EditResponse.php:**

       return view('backend.tests.edit')->with([
            'tests' => $this->tests
        ]);
### **in edit.blade.php:**

        Form::model($test, ['route' => ....

This gives an error when implementing edit view for a module.

**Comment by viralsolani** [comment]
@vrkansagara  Take the latest pull of master branch in the demo. it will fix the issue now.

**Comment by peterquentin** [comment]
[Demo](https://laravel-adminpanel.vrkansagara.in/) (the one from README.md) is broken again.

**Comment by vrkansagara** [comment]
I will it and let you know.

**Comment by noahheck** [comment]
I don't know if this got fixed, but it is not working at this time.

**Comment by vrkansagara** [comment]
@noahheck  and @peterquentin , Link is working. Please check.

**Comment by noahheck** [comment]
@vrkansagara The link is working now. Thanks!
