### ISSUE TITLE
login passwords are not working

### ISSUE THREAD

**Issue by Amrgumaa** [viralsolani/laravel-adminpanel#350]

**Comment by Amrgumaa** [comment]
hi I am unable to login with username and passwords for all users .is that an internal issue
![screen shot 2019-02-15 at 6 34 21 pm](https://user-images.githubusercontent.com/33161681/52870415-787b4500-3150-11e9-90f9-dda7e52de489.png)

**Comment by bvipul** [comment]
Can you please check the database table users, and see if they have entries in it. Maybe the seeding didn't go through well

**Comment by Amrgumaa** [comment]
The tables are seeded well as per attached picture .
![screen shot 2019-02-15 at 7 58 29 pm](https://user-images.githubusercontent.com/33161681/52875245-9babf180-315c-11e9-8e1a-4aa01e84fdeb.png)

**Comment by vrkansagara** [comment]
@Amrgumaa  Would you mind to migrate:Fresh again and start server, And let us share more details if you find any issue.

**Comment by Amrgumaa** [comment]
thanks working perfectly
