### ISSUE TITLE
Menu problem when add new module

### ISSUE THREAD

**Issue by gunjanbacancy** [viralsolani/laravel-adminpanel#351]
Hi,
I have 2 Role 1) Master Admin 2) Super Admin. When I add a new module name with 'news management' and it shows in 'Master Admin' not show for other users (e.g. Super Admin). I checked 'news management' (e.g. News Management, News Create, Edit News etc. in 'Associated Permissions')  in 'User Management' and 'Role Management'.  But 'News management' show in master admin only not show in 'Super Admin'.

Anyone please me !!

**Comment by bvipul** [comment]
Hello @gunjanbacancy, you probably have added a permission name while adding the menu, which is available for "Master Admin" and not in "Super Admin".

**Comment by gunjanbacancy** [comment]
It's working now. Thanks
