### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by invaders-xx** [viralsolani/laravel-adminpanel#353]
Hi all,

Are there any issues in upgrading to 5.8 ?

Many thanks in advance,

David.

**Comment by vrkansagara** [comment]
@indranshastri  This is in our next pip line so. We will update you on this.

**Comment by viralsolani** [comment]
I'll upgrade the project in laravel 5.8 in next two weeks

**Comment by invaders-xx** [comment]
great, many thanks,
Please let me know once done.

**Comment by invaders-xx** [comment]
Hi Guys,

Any news ?

Many thanks in advance for your feedback.

**Comment by henningerd** [comment]
> Hi Guys,
> 
> Any news ?
> 
> Many thanks in advance for your feedback.

I'm interested into it too.

**Comment by viralsolani** [comment]
You guys can check develop branch for that. I have already upgrade it to laravel 5.8.

As of now qe are testing all the  things and planning to add laravel passport and dusk test cases with this release.

**Comment by viralsolani** [comment]
the master branch is updated now with Laravel 5.8.

**Comment by invaders-xx** [comment]
Hi Guys,

Many thanks for your feedback. I did many developments on top of yours. Is there any easy way to update my local repo without loosing or crashing what I did ? Sorry but I am not familiar with git.

Many thanks in advance for your help.
