### ISSUE TITLE
checkUserByEmail in App\Repositories\Backend\Access\User\UserRepository

### ISSUE THREAD

**Issue by invaders-xx** [viralsolani/laravel-adminpanel#354]
Dear guys,

I think you should add withTrashed() in the query as it give an error if email already exists and trashed

BR

David

**Comment by invaders-xx** [comment]
and you should also add this test in the create function

**Comment by viralsolani** [comment]
@invaders-xx I am planning to add Laravel dusk test cases, with that I'll check this as well.

**Comment by vidhyut-pandya** [comment]
@invaders-xx  Your suggestion is implemented. Thanks.
