### ISSUE TITLE
login with username or email

### ISSUE THREAD

**Issue by ramkumawathis** [viralsolani/laravel-adminpanel#355]
Hi,
Am using this admin panel. Its too much help full . Please tell me how i can login with username or email.

**Comment by viralsolani** [comment]
@ramkumawathis as of now, we are allowing login through email. if you would like to login through username, this might be useful. https://laraveldaily.com/laravel-login-email-username-one-field/

**Comment by bvipul** [comment]
I think this one, we should do in our panel. Nowadays, almost everyone requires login through email/username/phonenumber. We can atleast provide username support. This will require some changes in the database as well. And YAYYY!! some more tests.

I will take up this task.

Thanks @ramkumawathis for suggestion.

**Comment by ramkumawathis** [comment]
> 
> 
> @ramkumawathis as of now, we are allowing login through email. if you would like to login through username, this might be useful. https://laraveldaily.com/laravel-login-email-username-one-field/

T

**Comment by ramkumawathis** [comment]
> 
> 
> @ramkumawathis as of now, we are allowing login through email. if you would like to login through username, this might be useful. https://laraveldaily.com/laravel-login-email-username-one-field/

Thanks @viralsolani  for your support.
I resolved my issue "login with username and email" with some changes.
Changes are 
-> add new function in login controller 
 protected function credentials(Request $request)
    {
        $field = filter_var($request->get($this->username()), FILTER_VALIDATE_EMAIL)
        ? $this->username()
        : 'username';

        return [
            $field => $request->get($this->username()),
            'password' => $request->password,
        ];
    }


-> Change email field type to text in login blade file.

That fine

**Comment by viralsolani** [comment]
@ramkumawathis Thanks. 

@bvipul  perfect. go ahead then.
