### ISSUE TITLE
Babel module build failed

### ISSUE THREAD

**Issue by VadimsTalapins** [viralsolani/laravel-adminpanel#356]
I cannot install after this command: npm run development
I have this errors
ERROR in ./resources/assets/js/backend/app.js
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

ERROR in ./resources/assets/js/plugin/sweetalert/sweetalert.min.js
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

ERROR in ./resources/assets/js/frontend/app.js
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

ERROR in ./resources/assets/js/plugins.js
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3".

npm -v 6.7.0
node -v v11.10.1

**Comment by viralsolani** [comment]
I am able to run npm run development. But I'll with node 11 once.

**Comment by VadimsTalapins** [comment]
I'll try to do downgrade

**Comment by viralsolani** [comment]
any update. please re-open the issue if the issue still persists.
