### ISSUE TITLE
Please Reset the Demo https://apiway.in/

### ISSUE THREAD

**Issue by vedbhawsar** [viralsolani/laravel-adminpanel#360]
@viralsolani @bvipul  @vrkansagara 
Can someone please reset the demo to initial state. Some who has access to https://apiway.in/ server.

**Comment by vrkansagara** [comment]
@vedbhawsar  done !

**Comment by vrkansagara** [comment]
This is happening because of https://github.com/viralsolani/laravel-adminpanel/issues/349
