### ISSUE TITLE
Can't give roles to user

### ISSUE THREAD

**Issue by jobferrera** [viralsolani/laravel-adminpanel#362]
Hello sir, i have a concern though the system is quite working for me very well, but when i created some modules and a user with the roles of the modules i created it doesn't seem to work. The only thing that works fine are the modules which are default created by you. Thank you in advanced.

**Comment by bvipul** [comment]
okay, that's a bold statement. Let us look at that. 
So, your scenario is that, when you assign module roles to a user, they don't see the assigned modules?

**Comment by jobferrera** [comment]
yes sir, the default modules was the only modules can be added to the user except the one i created. Is there something to do with events?

**Comment by jobferrera** [comment]
Thank you anyway for your quick response, i appreciate it.

**Comment by bvipul** [comment]
No, there maybe something with the permissions, let us check it out

**Comment by jobferrera** [comment]
Alright thank you so much

**Comment by justin22** [comment]
A similar case (may be same - User permission sync problem).
1. Created a new module.
2. Assigned new module permission to **user role** in roles management
3. But the users with **user role**  doesn't have the new module permission.

**Comment by krguptaa** [comment]
@jobferrera @justin22 For assigning the module permission to particular user. you need to edit that user and need to update the permission then it affect to particular user. If you add the module permission to role then it only for roles not to existing user.
