### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by rvigneshmdu** [viralsolani/laravel-adminpanel#363]
![npm](https://user-images.githubusercontent.com/48316291/54068432-bd3b5d00-4272-11e9-8d31-02bddac91e02.png)

**Comment by viralsolani** [comment]
@rvigneshmdu Please give us some more information. check an additional log from npm logs.

**Comment by maninest** [comment]
I also have the same issue, I put log below: 


`5028 warn img-loader@3.0.0 requires a peer of imagemin@^5.0.0 but none is installed. You must install peer dependencies yourself.
5029 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
5030 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
5031 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
5031 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
5031 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
5031 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
5032 verbose stack Error: webpack-rtl-plugin@1.8.1 postinstall: `./postinstall.sh`
5032 verbose stack Exit status 1
5032 verbose stack     at EventEmitter.<anonymous> (C:\Users\kr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
5032 verbose stack     at EventEmitter.emit (events.js:197:13)
5032 verbose stack     at ChildProcess.<anonymous> (C:\Users\kr\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
5032 verbose stack     at ChildProcess.emit (events.js:197:13)
5032 verbose stack     at maybeClose (internal/child_process.js:984:16)
5032 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
5033 verbose pkgid webpack-rtl-plugin@1.8.1
5034 verbose cwd C:\xampp\htdocs\ebay
5035 verbose Windows_NT 10.0.17134
5036 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kr\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
5037 verbose node v11.11.0
5038 verbose npm  v6.7.0
5039 error code ELIFECYCLE
5040 error errno 1
5041 error webpack-rtl-plugin@1.8.1 postinstall: `./postinstall.sh`
5041 error Exit status 1
5042 error Failed at the webpack-rtl-plugin@1.8.1 postinstall script.
5042 error This is probably not a problem with npm. There is likely additional logging output above.
5043 verbose exit [ 1, true ]`

**Comment by hijaumuda** [comment]
10 days ago i successfully installed, but now when i try to fresh install in different directory i got error.

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'development' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'predevelopment', 'development', 'postdevelopment' ]
5 info lifecycle @~predevelopment: @
6 info lifecycle @~development: @
7 verbose lifecycle @~development: unsafe-perm in lifecycle true
8 verbose lifecycle @~development: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;F:\laravel\GIT\laravel-adminpanel\node_modules\.bin;C:\Windows\System32;C:\Program Files\MongoDB\Server\4.0\bin;C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd;C:\Users\Dimas\AppData\Roaming\npm;C:\Program Files\nodejs;E:\xampp\php;C:\ProgramData\ComposerSetup\bin;
9 verbose lifecycle @~development: CWD: F:\laravel\GIT\laravel-adminpanel
10 silly lifecycle @~development: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js' ]
11 silly lifecycle @~development: Returned: code: 1  signal: null
12 info lifecycle @~development: Failed to exec development script
13 verbose stack Error: @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd F:\laravel\GIT\laravel-adminpanel
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "development"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
22 error Exit status 1
23 error Failed at the @ development script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by hijaumuda** [comment]
@rvigneshmdu @maninest @viralsolani 
i check this commit [https://github.com/viralsolani/laravel-adminpanel/commit/edef02f2f67c2ff790b7037275f270588faea5d3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2](url) /package.json
![vuewebpack](https://user-images.githubusercontent.com/8728222/54435843-f63c6b80-4763-11e9-8eb6-17a77bc369c4.png)
and i just back to previous version before commit (vue & webpack-rtl-plugin).

`npm uninstall vue --save
npm install vue@2.5.17 --save
and
npm uninstall webpack-rtl-plugin --save
npm install webpack-rtl-plugin@1.5.0 --save`

I don't know if this is the right way, but now it works!

**Comment by ramkumawathis** [comment]
Am also getting error for new setup
Error 
$ npm install
> webpack-rtl-plugin@1.8.1 postinstall D:\laravel-adminpanel\node_modules\webpack-rtl-plugin
> ./postinstall.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN img-loader@3.0.0 requires a peer of imagemin@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-rtl-plugin@1.8.1 postinstall: `./postinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack-rtl-plugin@1.8.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User1\AppData\Roaming\npm-cache\_logs\2019-03-20T09_42_57_414Z-debug.log

**Comment by bvipul** [comment]
Thanks @hijaumuda, your solution works, I will add a PR for this. @ramkumawathis you can also try this.

**Comment by bvipul** [comment]
Fixed in #375
