### ISSUE TITLE
Role Management index showing error

### ISSUE THREAD

**Issue by anushamarasani** [viralsolani/laravel-adminpanel#369]

**Comment by anushamarasani** [comment]
![123](https://user-images.githubusercontent.com/35235703/54417676-e2274880-4728-11e9-8175-4650b574b467.PNG)

**Comment by bvipul** [comment]
Can you please post the javascript and TableController code, it might be an issue in those files

**Comment by bvipul** [comment]
@anushamarasani Did you add of modify any roles, can you please tell what lead to this issue ?

**Comment by viralsolani** [comment]
Error resolved.
