### ISSUE TITLE
module generator does not create the same variable between EditResponse.php and edit.blade.php

### ISSUE THREAD

**Issue by hijaumuda** [viralsolani/laravel-adminpanel#370]
in EditResponse.php module generator always created variable end with "s" or "es" (according to table name created in the module generator).

but in edit.blade.php variable end without "s" or "es".

when i check at the faqs, it seems module generator create wrong variable name in EditResponse.php, It should be without the "s" or "es" suffix.

**Comment by bvipul** [comment]
Thanks, for pointing that out, I will see if that's actually the issue and fix it. Thanks again @hijaumuda

**Comment by bvipul** [comment]
This bug is fixed in develop branch and will be released soon.
