### ISSUE TITLE
SEO does not work

### ISSUE THREAD

**Issue by Aleintel** [viralsolani/laravel-adminpanel#372]
Hello,
SEO does not work,
how can i implement / fix?

Thanks

**Comment by viralsolani** [comment]
Can you elaborate? what do you mean by SEO is not working?

**Comment by Aleintel** [comment]
When I create a new page, I enter the title and all the information.
In the textarea SEO Title, SEO description ... when I enter the values, these I visualize them in the column of the database, and here everything is fine!

When I visualize the page that I have created, I don't see the meta, keywords and description .. How should I do to visualize them correctly

In app.balde.php I have:

         <meta charset = "utf-8">
         <meta http-equiv = "X-UA-Compatible" content = "IE = edge">
         <meta name = "viewport" content = "width = device-width, initial-scale = 1">
         <meta name = "csrf-token" content = "{{csrf_token ()}}">
         <title> @yield ('title', app_name ()) </title>

         <! - Meta ->
         <meta name = "description" content = "@ yield ('meta_description', 'Laravel AdminPanel')">
         <meta name = "author" content = "@ yield ('meta_author', 'Viral Solani')">
         @yield ('meta')

**Comment by Aleintel** [comment]
When I create a new page, I enter the title and all the information.
In the textarea SEO Title, SEO description ... when I enter the values, these I visualize them in the column of the database, and here everything is fine!

When I visualize the page that I have created, I don't see the meta, keywords and description .. How should I do to visualize them correctly

In app.balde.php I have:

```
         <meta charset = "utf-8">
         <meta http-equiv = "X-UA-Compatible" content = "IE = edge">
         <meta name = "viewport" content = "width = device-width, initial-scale = 1">
         <meta name = "csrf-token" content = "{{csrf_token ()}}">
         <title> @yield ('title', app_name ()) </title>

         <! - Meta ->
         <meta name = "description" content = "@ yield ('meta_description', 'Laravel AdminPanel')">
         <meta name = "author" content = "@ yield ('meta_author', 'Viral Solani')">
         @yield ('meta')
```

**Comment by viralsolani** [comment]
ok, I'll fix it asap. Thanks for raising this issue.

**Comment by Aleintel** [comment]
I am waiting for your feedback.
thanks a lot

Aleintel

**Comment by vidhyut-pandya** [comment]
@Aleintel This issue is fixed. You can take a pull from the develop branch. 
Also, just FYI, you can have your own meta tags, just put your meta tags in any blade file which is extending the `app` layout and put them inside the `meta` section. 

For example:

`@section('meta') `
` // your meta tags`
`@endsection`

**Comment by Aleintel** [comment]
Thank you very much!
How can I do a pull from the develop branch?
Can you explain me please?

Thank you.
