### ISSUE TITLE
Vue Package Issue

### ISSUE THREAD

**Issue by vaghela943** [viralsolani/laravel-adminpanel#374]
I have setup all the things. but it show me errors as below.

`Error: Module build failed: Error: 

Vue packages version mismatch:

- vue@2.6.8
- vue-template-compiler@2.5.17

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
`

**Comment by bvipul** [comment]
Fixed in #375
