### ISSUE TITLE
Vue version miss-match

### ISSUE THREAD

**Issue by Gautam-Patel** [viralsolani/laravel-adminpanel#376]
error  in ./resources/assets/js/components/Flash.vue
Module build failed
vue@2.6..8
vue-template-compiler@2.5.17

**Comment by bvipul** [comment]
Please see #375

**Comment by chrizz1001** [comment]
Hi, the fix #375 does not fix this for me. I tried to completely reinstall all node modules with the fix but still the same issue. I also tried complete fresh installation. Same issue...

**Comment by viralsolani** [comment]
can you guys tell me your node version?

**Comment by viralsolani** [comment]
the issue is fixed now. Please run _npm cache clear --force_.
