### ISSUE TITLE
invalid upload request

### ISSUE THREAD

**Issue by kocuubirasap** [viralsolani/laravel-adminpanel#381]
can't upload file use filemanager and error with invalid upload request

**Comment by bvipul** [comment]
can you please check if you are uploading a file too large...

**Comment by kocuubirasap** [comment]
My image only 62 kb sir

**Comment by viralsolani** [comment]
@kocuubirasap ok, we will look into this.

**Comment by viralsolani** [comment]
I am able to upload the image. can you please give us error screenshot, please?

**Comment by vidhyut-pandya** [comment]
@kocuubirasap  It seems to be working fine on our side. If you are still facing the issue, do reopen the the same. Closing for now.
