### ISSUE TITLE
CamelCase when create double name in Module Section

### ISSUE THREAD

**Issue by naninmartins** [viralsolani/laravel-adminpanel#382]
When I create a new module with two names the files generated can't reproduce CamelCase ie:
Directory Name: CarCategories
Model Name: CarCategory
I assume to have names like :
App\Http\Controllers\CarCategor**ies**\Car**C**ategoriesController.php
But instead I had:
App\Http\Controllers\CarCategor**y**\Car**c**ategoriesController.php

**Comment by bvipul** [comment]
This might be because of the latest changes pushed in the generator package. I will have a look. Thanks @naninmartins .

**Comment by bvipul** [comment]
Fixed the bug in generator package in v5.8.2 of bvipul/generator. #449
