### ISSUE TITLE
Login issue with new created user

### ISSUE THREAD

**Issue by msspiritgit** [viralsolani/laravel-adminpanel#385]
Hi,

We have created a user from admin panel but user not login through front end and backend, showing wrong credentials.

There is password issue, login system working only with the three user created by you in repository. New created user can't login please reply me as soon as possible.

Thanks
Mukesh

**Comment by msspiritgit** [comment]
Hi team, 

No need to reply on this, I have resolved this issue myself.

Thanks

**Comment by anantajitjg** [comment]
@bvipul 
This issue still exists within the app.

There is no need to use the bcrypt method. If you use that function hashing will occur twice.

Please [refer here](https://github.com/rappasoft/laravel-5-boilerplate/blob/master/app/Repositories/Backend/Auth/UserRepository.php#L186).

**Comment by paragonsoftwaresolutions** [comment]
> Hi team,
> 
> No need to reply on this, I have resolved this issue myself.
> 
> Thanks

Mind sharing how you resolved this?
