### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by Parkbyounghyo** [viralsolani/laravel-adminpanel#388]
composer -v 
Composer version 1.8.4 2019-02-11 10:52:10

composer install 

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In EncryptionServiceProvider.php line 44:

  No application encryption key has been specified.

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by ZWindL** [comment]
same error here, and I tried to execute commands manually, didn't work either.

**Comment by manishpanchal** [comment]
In EncryptionServiceProvider.php line 44:

  No application encryption key has been specified.


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by manishpanchal** [comment]
can u solve this ??

**Comment by thomasgit123** [comment]
@manishpanchal , if you try to add APP_KEY(should be base64 format or key from other laravel project env) on .env file and try to run php artisan key:generate, it will generate new key and works fine

**Comment by commentatorboy** [comment]
Just write f.x. this in the APP_KEY in the .env file:
`base64:uOgWdZUJhtOScNZ5n+4FWN0gchPHCQP3NVEs4S+wzDo=`

**Comment by bvipul** [comment]
No need to add this ... Just run key:generate it will generate that key

**Comment by commentatorboy** [comment]
Really? Weird. Because when I tried to run that, it would still say the same error. It only works when I add a key.

**Comment by hemantshekhawat** [comment]
> Just write f.x. this in the APP_KEY in the .env file:
> `base64:uOgWdZUJhtOScNZ5n+4FWN0gchPHCQP3NVEs4S+wzDo=`
> and then run `php artisan key:generate `

This one worked !
