### ISSUE TITLE
Composer install error and view flash message error

### ISSUE THREAD

**Issue by pankaj-snow** [viralsolani/laravel-adminpanel#389]

**Comment by viralsolani** [comment]
Please provide some screenshot so it will help us to identify errors. also, let us know your PHP version, please.

**Comment by khajahcode** [comment]
same problem here , will share screen shot

**Comment by khajahcode** [comment]
![Screen Shot 2019-07-08 at 12 44 32 PM](https://user-images.githubusercontent.com/20269708/60800638-3776e200-a17e-11e9-8fa9-ed534ca468c0.png)

**Comment by viralsolani** [comment]
@khajahcode Please take the latest pull and check once again. it should fix the error.
