### ISSUE TITLE
Admin Access User error

### ISSUE THREAD

**Issue by rebornishard** [viralsolani/laravel-adminpanel#39]
admin/access/user

SQL error user.first_name isn't in group by

[https://ctrlv.cz/shots/2017/11/25/zmEt.png](url)

**Comment by viralsolani** [comment]
Hello @rebornishard 

Take the latest pull of master branch. 

Regenerate migration and seeders once

And check again. I've refactored whole backend user module.

**Comment by bvipul** [comment]
This issue is still not resolved, as I am also getting the same error in my machine. We need to fix this.

**Comment by bvipul** [comment]
Added the PR. @viralsolani Please review and merge.

**Comment by trollid** [comment]
<< i'm another account of @rebornishard 
thanks @bvipul

**Comment by bvipul** [comment]
@rebornishard @trollid Did that solve your problem ?

**Comment by trollid** [comment]
@bvipul hold on update composer & npm install

**Comment by trollid** [comment]
@bvipul confirmed fixed, @viralsolani please
@bvipul thanks a lot

what i need for now is complete doc or guide how to expand or use

**Comment by bvipul** [comment]
@trollid Everything is there in the Readme file of this project. If you find any issues and have some suggestion. Please mail me at basapativipulkumar@gmail.com or viral.solani@gmail.com
