### ISSUE TITLE
Fatal error: Class 'Arcanedev\LogViewer\Contracts\Utilities\Filesystem' not found

### ISSUE THREAD

**Issue by johnny7707** [viralsolani/laravel-adminpanel#390]
Fatal error: Class 'Arcanedev\LogViewer\Contracts\Utilities\Filesystem' not found in C:\xampp\htdocs\adminpanel\config\log-viewer.php on line 17

**Comment by vidhyut-pandya** [comment]
@johnny7707  Provide some screenshots or steps to reproduce.

**Comment by vidhyut-pandya** [comment]
Closing this issue as not reproducible. @johnny7707  do re-open the issue if you are still facing it,
