### ISSUE TITLE
Delete not working 

### ISSUE THREAD

**Issue by erparthqa** [viralsolani/laravel-adminpanel#394]
I have created new module as contact and trying to delete but it’s showing me details instead of deleting records.
Same issue occurred in all others module which default in admin

**Comment by vidhyut-pandya** [comment]
@erparthqa If possible, provide more details as we are not able to re-produce this issue.

**Comment by krguptaa** [comment]
@erparthqa Delete is working fine with new created module as well as existing module. Can you please describe little bit more about your issue.

**Comment by viralsolani** [comment]
@erparthqa Please check once. this issue has been resolved.
