### ISSUE TITLE
Language option and Logout button invisible

### ISSUE THREAD

**Issue by tpw1314** [viralsolani/laravel-adminpanel#397]
Issue description : Language option (French in this case) and Logout button is blank due to the text color being white in Responsive Mode/iOS screen and actual iPhone.
Screenshots:
![image](https://user-images.githubusercontent.com/20537849/57598356-7b39da80-7585-11e9-92be-35f2339be1c5.png)
![image](https://user-images.githubusercontent.com/20537849/57598375-8c82e700-7585-11e9-8f2f-581e7f3f4a1c.png)

Extra description : Both are visible only when mouse hover on it. Probably just CSS/SCSS issue.

So anyone wants to fix this or I will volunteer but it may takes awhile since this is my first setup of this panel.

**Comment by tpw1314** [comment]
hi all, anyone looking into this issue ?

**Comment by bayubimantarar** [comment]
Let me try to fix this issues please.
