### ISSUE TITLE
Permission is not working

### ISSUE THREAD

**Issue by sathiyaraj1989** [viralsolani/laravel-adminpanel#398]
Still we could see the menu(FAQ) displaying in sidebar after removing the permission for executive role in Access Management->Role Management.

Do I need to run anything behind, after removing permission for any menus from Access Management->Role Management?

**Comment by sathiyaraj1989** [comment]
Any updates on this issue ?

**Comment by vidhyut-pandya** [comment]
@sathiyaraj1989  It seems to be working fine on our side. Provide more details if possible.
