### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by Gautam-Patel** [viralsolani/laravel-adminpanel#402]
Run application in windows and install npm error found npm ERR! code ELIFECYCLE.

**Comment by joelderrickclad** [comment]
I added **"C:\Windows\System32"** path to environment variable list and restarted the machine. It worked for me.

Please refer this [link ](https://stackoverflow.com/a/57511535/5352831)

**Comment by viralsolani** [comment]
Check the latest pull of master branch and it should work.
