### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by mattfletcher** [viralsolani/laravel-adminpanel#403]
Logged in successfully to a fresh install with admin@admin.com:1234

Set up a new Administrator user with my own email address

Log out

Log in as new user

Redirected back to empty log in form

No errors in storage/logs/laravel.log

Tried migrate:fresh and db:seed, and recreating new user. No difference.

If I do a forgotten password, following the link in the email and resetting password WILL log me in, but again, after logging out, cannot log back in again using normal login form.

**Comment by marcusAutoSquared** [comment]
This was caused for me by the password being hashed twice when creating a new user or updating a password, once  in 

> UserRepository.createUserStub
> or 
> UserRepository.updatePassword 

and again in

> User.setPasswordAttribute.

I've fixed this by changing `$user->password = bcrypt($input['password']);` to `$user->password = $input['password'];` in both createUserStub and updatePassword. The password in the database is still hashed and secure, a logging in now works fine.

**Comment by vidhyut-pandya** [comment]
Fixed this issue and currently merged in develop branch. closing this issue. Let us know if the issue still persists.
