### ISSUE TITLE
Need help creating events

### ISSUE THREAD

**Issue by RohanMhz** [viralsolani/laravel-adminpanel#404]
I want to create an event for created, updated and deleted package action.
but it shows error as:
An invalid history type was supplied: Package

Is there something that I forgot to do? help me, please

**Comment by bvipul** [comment]
You need to add an entry for 'Package' in your historyType table

**Comment by RohanMhz** [comment]
I already did that. anything else???

**Comment by RohanMhz** [comment]
oh i forgot to add it in the table. thanks for the help tho
