### ISSUE TITLE
Route [frontend.auth.login] not defined.

### ISSUE THREAD

**Issue by LincolnTK** [viralsolani/laravel-adminpanel#409]
![image](https://user-images.githubusercontent.com/51019232/59648969-23445400-9181-11e9-9510-4b4a7d00051e.png)

**Comment by vidhyut-pandya** [comment]
@LincolnTK  Have you made any changes in nav file or in your routes file? It seems to be working on our side. Do run `php artisan config:cahe` from terminal and check again.
