### ISSUE TITLE
Fatal error: require

### ISSUE THREAD

**Issue by collohdicey** [viralsolani/laravel-adminpanel#413]
![image](https://user-images.githubusercontent.com/36438012/59994065-2ba5fe80-965b-11e9-84ca-2a1b159e179a.png)
i keep getting this error: Fatal error: require(): Failed opening required 'C:\Users\Social Media\laravel-adminpanel\bootstrap/../vendor/autoload.php' (include_path='C:\xampp
\php\PEAR') in C:\Users\Social Media\laravel-adminpanel\bootstrap\autoload.php on line 17.

kindly assist.

**Comment by bvipul** [comment]
This is nothing related to out package, your PHP installation might not be correct. Please try installing laravel basic installation on your machine, then install this package.
