### ISSUE TITLE
Removing public form url

### ISSUE THREAD

**Issue by ashutosh2801** [viralsolani/laravel-adminpanel#414]
When we remove public from url, data does not show in backend or does not register record from frontend. 

http://localhost/laravel-adminpanel/public/admin/dashboard - it is working fine
http://localhost/laravel-adminpanel/admin/dashboard - record does not show

Please help

**Comment by viralsolani** [comment]
@ashutosh2801 you need to create the virtual host or run 

> php artisan serve

 from your root folder.
