### ISSUE TITLE
Index View - Export All Rows

### ISSUE THREAD

**Issue by baduypaltalk** [viralsolani/laravel-adminpanel#420]
Hi, @bvipul  @viralsolani 

Could you please tell me how to export all rows on index views of a generated module.

![image](https://user-images.githubusercontent.com/8188362/60937027-4b931e80-a2f9-11e9-9cb6-d0b27f2074f1.png)

Thanks

**Comment by baduypaltalk** [comment]
I saw the Datatable documents and apply this code, but it does not change.

![image](https://user-images.githubusercontent.com/8188362/60937186-b04e7900-a2f9-11e9-8db2-9bfcf0892bde.png)

**Comment by krguptaa** [comment]
@baduypaltalk You need to add  "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]] in Datatable and select all option from page length dropdown and then export.
