### ISSUE TITLE
ERROR: for laravel-adminpanel_mysql_1_5739fe9a3285  Cannot start service mysql: driver failed programming external connectivity on endpoint laravel-adminpanel_mysql_1_5739fe9a3285

### ISSUE THREAD

**Issue by Gautam-Patel** [viralsolani/laravel-adminpanel#443]
* docker-compose up --build it is given error can not start service mysql.

**Comment by Gautam-Patel** [comment]
When deploying with docker application it's take too much time.

**Comment by viralsolani** [comment]
@Gautam-Patel Dockerize this project is still in progress. I'll fix all the bugs in the future.  you can always give a PR in develop branch if you would like to thanks.
