### ISSUE TITLE
View not found issue

### ISSUE THREAD

**Issue by sukhwinderkaur1389** [viralsolani/laravel-adminpanel#455]
"The Mix manifest does not exist. (View: /home/si3qbnjvhf89/public_html/resources/views/frontend/layouts/app.blade.php) (View: /home/si3qbnjvhf89/public_html/resources/views/frontend/layouts/app.blade.php) ◀"

**Comment by bvipul** [comment]
This is a duplicate issue, you should first search the issue in the repository issues list.  You will find the solution there.

**Comment by sukhwinderkaur1389** [comment]
Please provide me a solution , I am not getting in issues

**Comment by bvipul** [comment]
You are getting issue in running the `npm run dev` command, please follow strictly the readme file. And please check if you are getting errors in the above command.

**Comment by sukhwinderkaur1389** [comment]
Hi,
Please give the solution , I am not getting the  issue.

**Comment by bvipul** [comment]
Is `npm run dev` command giving any errors?

**Comment by sukhwinderkaur1389** [comment]
I haven't run this , why we need this? as its laravel App application.

**Comment by sukhwinderkaur1389** [comment]
[image: image.png]
Login will look like this?
No like : http://demo.joshadmin.com/admin/signin

**Comment by bvipul** [comment]
This just states that you haven't followed readme.. please follow it, each step is important

**Comment by sukhwinderkaur1389** [comment]
Please share link.

**Comment by sukhwinderkaur1389** [comment]
Hi,
I have cpanel and I can't run npm command. and other solution?

**Comment by bvipul** [comment]
Sorry, no other solution, you can try installing nvm
