### ISSUE TITLE
Tiny MCE not working

### ISSUE THREAD

**Issue by AshwinPitroda** [viralsolani/laravel-adminpanel#463]
Tiny MCE editor is not working. I checked recent commits and i found that Tiny MCE library  is updated with version 5.  I also checked change log in tinyMCE and found that they removed modern theme in latest version and now only one theme is available that is silver.
In this repo i checked still modern theme is used in admin.js and frontend.js. So, It's not finding modern theme and Tiny MCE not working.

**Comment by viralsolani** [comment]
ok thanks, @AshwinPitroda I'll look into it.

**Comment by agungasmara** [comment]
Hi, tiny MCE still not working

**Comment by krguptaa** [comment]
I've fixed this issue. check the develop branch once pull request is merged. you just need to change the theme of tinymce from modern to silver as it is not available in latest version.

**Comment by viralsolani** [comment]
Resolved.
