### ISSUE TITLE
textarea appear as empty

### ISSUE THREAD

**Issue by mohamed4shim** [viralsolani/laravel-adminpanel#472]
![image](https://user-images.githubusercontent.com/5725759/65914944-ab6a0480-e3d2-11e9-8b80-952591a4dc7c.png)

how i can show tinymyce editor

**Comment by krguptaa** [comment]
I've fix this issue. check the develop branch once pull request is merged. you just need to change the theme of tinymce from modern to silver as it is not available in latest version.

**Comment by viralsolani** [comment]
Resolved.
