### ISSUE TITLE
export button doesn't appear

### ISSUE THREAD

**Issue by mohamed4shim** [viralsolani/laravel-adminpanel#473]
who i can appear header export buttons 
@if(Active::checkUriPattern('admin/faqs'))
    <export-component></export-component>
@endif
doesn't appear buttons

**Comment by krguptaa** [comment]
Hello @mohamed4shim,

We fixed the issue. Kindly take the pull of develop branch.

**Comment by mohamed4shim** [comment]
thanks for your replay
but can you send me the url of the working verision?

**Comment by krguptaa** [comment]
@mohamed4shim you can try on demo URL (https://laravel-adminpanel.vrkansagara.in/) which is available in Readme.
