### ISSUE TITLE
Unable to install on our computer

### ISSUE THREAD

**Issue by dukeappss** [viralsolani/laravel-adminpanel#498]
I tried ti install this on our local server through the instruction you shard. But i am not able to install. please share me steps.
![lv2](https://user-images.githubusercontent.com/56361574/66504916-e01f3f80-eae7-11e9-8f2c-3500444932e4.png)
![lv](https://user-images.githubusercontent.com/56361574/66504917-e0b7d600-eae7-11e9-8f4e-1a4c0999e086.png)

**Comment by viralsolani** [comment]
it seems that you have not run composer install. please run manually all the steps.
