### ISSUE TITLE
Class 'Krgupta\Active\ActiveServiceProvider' not found

### ISSUE THREAD

**Issue by mfcRogue** [viralsolani/laravel-adminpanel#515]
On attempt to run through the installation 

both composer install and php artisan install:app

show the following error

In ProviderRepository.php line 208:

  Class 'Krgupta\Active\ActiveServiceProvider' not found

Attempting to load the site shows : 

Target [Spatie\Cors\CorsProfile\CorsProfile] is not instantiable while building [Spatie\Cors\Cors].

**Comment by krguptaa** [comment]
We are checking. Thanks @mfcRogue Will update you asap.

**Comment by krguptaa** [comment]
@mfcRogue  We fixed the issue. Please take the latest code from repository and again try to install. It will work. 

Kindly let us know if any query or concern. 

Thank you.
