### ISSUE TITLE
Question about CRUD Generate

### ISSUE THREAD

**Issue by alexsantm2019** [viralsolani/laravel-adminpanel#524]
To create a new CRUD (forms, Controller, etc) I built a new table with some fields, but when I generate "module", this was created without the fields I built. My question is, May I have to create manually the fields in each form, and configurate Models, Repositories etc??

Thanks in advanced

**Comment by bvipul** [comment]
Currently the Generator module only creates a scaffolding of files and folders for you, it does not integrate with external data. You will have to write fields in each form and configure model with relationships and other attributes(if necessary). All the code to insert/retrieve has been written for convenience.
