### ISSUE TITLE
No application encryption key has been specified

### ISSUE THREAD

**Issue by salomon16** [viralsolani/laravel-adminpanel#525]
I got No application encryption key has been specified when running composer install

**Comment by bvipul** [comment]
please do, `php artisan key:generate` before running `composer install`

**Comment by salomon16** [comment]
Thank you for reply, when i run php artisan key:generate, it's show failed to open stream: No such file or directory in bootstrap\autoload.php on line 17

**Comment by suhailkc** [comment]
I have the same issue. Is there any solution???
