### ISSUE TITLE
when creating New modules

### ISSUE THREAD

**Issue by rajamid** [viralsolani/laravel-adminpanel#528]
Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined function Bvipul\Generator\Repositories\title_case() 

when creating modules

**Comment by krguptaa** [comment]
Thanks @rajamid. We will check and update you asap.

**Comment by minutmorph** [comment]
any progress on this? thanks

**Comment by louisjjs** [comment]
Me too getting the same error. A fix for this would help test the package.

**Comment by georgechitechi** [comment]
Same here, Any Help
Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined function Bvipul\Generator\Repositories\title_case()

**Comment by louisjjs** [comment]
> Me too getting the same error. A fix for this would help test the package.

The "title_case()  " error is gone now, but getting the following error now
"Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) "

**Comment by xuandung38** [comment]
https://github.com/bvipul/generator/pull/9
Check this

**Comment by louisjjs** [comment]
Thanks Xuan, that fixed the issue for me.

**Comment by alexsantm2019** [comment]
How did you fix?? I have the same issue and I can not solve please.

**Comment by bvipul** [comment]
@viralsolani please change the composer.json for v6 of generator, so this issue can be closed.

**Comment by krguptaa** [comment]
Thanks @bvipul We have created the PR (https://github.com/viralsolani/laravel-adminpanel/pull/554).

**Comment by krguptaa** [comment]
@alexsantm2019 Fixed this issue. Thanks.
