### ISSUE TITLE
Error Adding User

### ISSUE THREAD

**Issue by georgechitechi** [viralsolani/laravel-adminpanel#538]
Unable to save User Due to Attached Error. Any Clues Where the code broke?

![capture_20191110015405](https://user-images.githubusercontent.com/52364198/68535536-50c2b180-035d-11ea-81bc-803a8ca91997.png)

**Comment by viralsolani** [comment]
ok, we will look into it asap.

**Comment by krguptaa** [comment]
Hi @georgechitechi ,

Thanks for letting us know. We have fixed the issue. Kindly get the pull of latest code and try again.

**Comment by georgechitechi** [comment]
Thanks @krguptaa. It's fine now
