### ISSUE TITLE
Laravel 6

### ISSUE THREAD

**Issue by izoj2013** [viralsolani/laravel-adminpanel#570]
Wanted to know if your adminpanel is already compatible with laravel 6. Alternatively, what is the process of upgrading an existing project such as your demo project (laravel-adminpanel) to working with laravel 6.x?

Rgds.-

**Comment by krguptaa** [comment]
Hello @izoj2013 ,

Yes. This adminpanel is compatible with Laravel 6.0. 

You have two options for upgrading Laravel 6.x
1. Using Laravel shift (https://laravelshift.com/). It is paid but it will upgrade your system fast and easy way. just need to change the configuration 

2. Using Manual, You need do manually by changing the laravel/framework dependency to 6.* in your composer.json file version. Please go through the link https://laravel.com/docs/6.x/upgrade

Kindly update us if any query or concern. 

We are happy to help you.

**Comment by krguptaa** [comment]
closing this issue.

**Comment by izoj2013** [comment]
Many thanks for your feedback.
Regards.
Iz.

    On Thursday, December 12, 2019, 6:34:01 PM GMT+2, Kamlesh Gupta <notifications@github.com> wrote:  
 
 
closing this issue.
