### ISSUE TITLE
The GET method is not supported for this route. Supported methods: POST

### ISSUE THREAD

**Issue by bangtiray** [viralsolani/laravel-adminpanel#573]
i'm getting The GET method is not supported for this route. Supported methods: POST error when using API reset password 
<img width="322" alt="1Untitled" src="https://user-images.githubusercontent.com/6264098/70873847-28744580-1fe2-11ea-9d3f-a0c975aad7e1.png">

with error like this
<img width="800" alt="2Untitled" src="https://user-images.githubusercontent.com/6264098/70873861-30cc8080-1fe2-11ea-91d6-acc832400b73.png">

**Comment by krguptaa** [comment]
Issue Fixed.  Please check
