### ISSUE TITLE
Error encryption key before composer install

### ISSUE THREAD

**Issue by deyvsonaguiar** [viralsolani/laravel-adminpanel#576]
I followed the installation instructions but before running the "php artisan install: app" command I wanted to generate the Laravel key and came across this error.
Some commands executed to try to correct, without solution were:
-composer install
- composer update
- composer update -lock s

Any ideia for solution?

See the log of error:

`   RuntimeException  : No application encryption key has been specified.

  at F:\laragon\www\disk-admin2\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:44
    40|     protected function key(array $config)
    41|     {
    42|         return tap($config['key'], function ($key) {
    43|             if (empty($key)) {
  > 44|                 throw new RuntimeException(
    45|                     'No application encryption key has been specified.'
    46|                 );
    47|             }
    48|         });

  Exception trace:

  1   Illuminate\Encryption\EncryptionServiceProvider::Illuminate\Encryption\{closure}("")
      F:\laragon\www\disk-admin2\vendor\laravel\framework\src\Illuminate\Support\helpers.php:422

  2   tap("", Object(Closure))
      F:\laragon\www\disk-admin2\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php:48

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

**Comment by krguptaa** [comment]
Hello @deyvsonaguiar ,
Please perform below step to fix the issue.

1. update the APP_KEY with below
APP_KEY=base64:yGt894Zmq4S+QhrATlf88p2E7M9FE1fR+aq6acvdNjs=

2. Try to update composer with below command
composer update

It will fix the problem. Please let us know if any query or concern.

Thank you.

**Comment by krguptaa** [comment]
Fixed the issue.

Closing the ticket
