### ISSUE TITLE
cant load uploaded image

### ISSUE THREAD

**Issue by syafiqwahid** [viralsolani/laravel-adminpanel#580]
hi there, i am succesfull upload new image howver it wont acessible... i tried everything to fetch uploaded imaged but still fail. please do assist me asap...... tq

Forbidden
You don't have permission to access /laravel-adminpanel/public/storage/img/logo/1577418463avatar-icon-png-8.jpg on this server.

**Comment by krguptaa** [comment]
Hi @syafiqwahid ,

Thanks for getting touch with us!

Please give the permission to storage and public folder.

**Comment by abdul191993** [comment]
how can i give the permission to storage and public folder..???

**Comment by abdul191993** [comment]
can you explain it more..??

**Comment by krguptaa** [comment]
Hello @abdul191993 

Please refer the below link

https://devanswers.co/how-to-view-file-and-folder-permissions-in-ubuntu/
https://askubuntu.com/questions/1104865/change-permissions-of-windows-mounted-folder-from-linux

Thnks
