### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError Call to undefined function Bvipul\Generator\Repositories\title_case() 

### ISSUE THREAD

**Issue by SliceCut** [viralsolani/laravel-adminpanel#581]
Bvipul\Generator\Repositories\ModuleRepository::create :56
C:\xampp\htdocs\laravel\laravel-adminpanel\vendor\bvipul\generator\src\Repositories\ModuleRepository.php:56

     * @throws GeneralException

     *

     * @return bool

     */

    public function create(array $input, array $permissions)

    {

        $module = Module::where('name', $input['name'])->first();

 

        if (!$module) {

            $name = $input['model_name'];

            $model = strtolower($name);

 

            foreach ($permissions as $permission) {

                $perm = [

                    'name'         => $permission,

                    'display_name' => title_case(str_replace('-', ' ', $permission)).' Permission',

                ];

                //Creating Permission

                $per = Permission::firstOrCreate($perm);

            }

 

            $mod = [

                'view_permission_id' => "view-$model-permission",

                'name'               => $input['name'],

                'url'                => 'admin.'.str_plural($model).'.index',

                'created_by'         => access()->user()->id,

            ];

 

            $create = Module::create($mod);

 

            return $create;

**Comment by krguptaa** [comment]
Hi @SliceCut ,

Have you working with latest code.? We already fixed this issue with recent update.

**Comment by SliceCut** [comment]
Should update composer?? Or again pull form ur github

**Comment by krguptaa** [comment]
First Get the pull from github and then after update the composer
