### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by hifce** [viralsolani/laravel-adminpanel#61]
class FrontendController extends Controller
{
    /**
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $settingData = Setting::first();
        $google_analytics = $settingData->google_analytics;

The last line throws this error:
Trying to get property of non-object.

This is a fresh install of laravel-adminpanel.

Thank you in advance!

Regards

**Comment by tommycox** [comment]
Be sure that `php artisan db:seed` has run correctly. This should populate the settings table. I had an issue with running `db:seed` myself, hitting an error in `EmailTemplatePlaceholderTableSeeder`.

```
Seeding: EmailTemplatePlaceholderTableSeeder

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: truncate ``)


In PDOConnection.php line 79:

                'updated_at' => Carbon::now(),
  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''


In PDOConnection.php line 77:

  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''
```

For the sake of testing, I commented out `DB::table(config('module.email_templates.placeholder_table'))->truncate();` and `DB::table(config('module.email_templates.placeholder_table'))->insert($data);` in `EmailTemplatePlaceholderTableSeeder.php`.

**Comment by viralsolani** [comment]
Thanks, @tommycox for resolving this issue.
