### ISSUE TITLE
Error in install proccess in windows 10, laravel 7, php 7

### ISSUE THREAD

**Issue by sernovelli** [viralsolani/laravel-adminpanel#640]
This error:

PHP Fatal error:  require(): Failed opening required 'F:\projetos\engerisco\jornada\laravel-adminpanel\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in F:\projetos\engerisco\jornada\laravel-adminpanel\bootstrap\autoload.php on line 17

when runned the command:

php artisan install:app

**Comment by bangtiray** [comment]
Running comman composer install
