### ISSUE TITLE
Error in Role Management while editing any role

### ISSUE THREAD

**Issue by bvipul** [viralsolani/laravel-adminpanel#7]
There is an error while editing any role.

You can find the stacktrace below:
ErrorException thrown with message "Undefined variable: role_permissions (View: /var/www/html/laravel-adminpanel/resources/views/backend/access/roles/edit.blade.php)"

Stacktrace:
#73 ErrorException in /var/www/html/laravel-adminpanel/storage/framework/views/811ca5a706a13df909f8b17ed5cfa3f25932431c.php:54
#72 {main} in /var/www/html/laravel-adminpanel/public/index.php:0
#71 ErrorException in /var/www/html/laravel-adminpanel/storage/framework/views/811ca5a706a13df909f8b17ed5cfa3f25932431c.php:54
#70 Illuminate\Foundation\Bootstrap\HandleExceptions:handleError in /var/www/html/laravel-adminpanel/storage/framework/views/811ca5a706a13df909f8b17ed5cfa3f25932431c.php:54
#69 include in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:43
#68 Illuminate\View\Engines\PhpEngine:evaluatePath in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:59
#67 Illuminate\View\Engines\CompilerEngine:get in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/View/View.php:137
#66 Illuminate\View\View:getContents in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/View/View.php:120
#65 Illuminate\View\View:renderContents in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/View/View.php:85
#64 Illuminate\View\View:render in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Http/Response.php:39
#63 Illuminate\Http\Response:setContent in /var/www/html/laravel-adminpanel/vendor/symfony/http-foundation/Response.php:201
#62 Symfony\Component\HttpFoundation\Response:__construct in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:711
#61 Illuminate\Routing\Router:toResponse in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:685
#60 Illuminate\Routing\Router:prepareResponse in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:645
#59 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#58 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/app/Http/Middleware/RouteNeedsPermission.php:41
#57 App\Http\Middleware\RouteNeedsPermission:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#56 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#55 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/app/Http/Middleware/SessionTimeout.php:59
#54 App\Http\Middleware\SessionTimeout:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#53 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/app/Http/Middleware/RouteNeedsPermission.php:41
#51 App\Http\Middleware\RouteNeedsPermission:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/app/Http/Middleware/LocaleMiddleware.php:57
#48 App\Http\Middleware\LocaleMiddleware:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#45 Illuminate\Routing\Middleware\SubstituteBindings:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#42 Illuminate\Auth\Middleware\Authenticate:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:67
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#33 Illuminate\Session\Middleware\StartSession:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#24 Illuminate\Pipeline\Pipeline:then in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:647
#23 Illuminate\Routing\Router:runRouteWithinStack in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:622
#22 Illuminate\Routing\Router:runRoute in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:588
#21 Illuminate\Routing\Router:dispatchToRoute in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Router.php:577
#20 Illuminate\Routing\Router:dispatch in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php:65
#17 Barryvdh\Debugbar\Middleware\InjectDebugbar:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#14 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:30
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:46
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:149
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:102
#2 Illuminate\Pipeline\Pipeline:then in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/html/laravel-adminpanel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/html/laravel-adminpanel/public/index.php:52

**Comment by viralsolani** [comment]
Resolved
