### ISSUE TITLE
Design of backend needs to have better color combination.

### ISSUE THREAD

**Issue by bvipul** [viralsolani/laravel-adminpanel#75]
We have focused mainly on our functionality and not on how our design is looking. So, if anybody can assist us in changing or altering the color theme with a good one. We will appreciate it.

For doing changes in CSS of the project, you need to update the custom-style.css file in public/css folder.
You can run `npm run watch` to do changes and not do `npm run dev` again and again.
You will have to do above as our custom style file is in webpack.js.

Thanks for your help.
Looking forward.

**Comment by viralsolani** [comment]
For now, we will stick with AdminLTE. in future we will integrate any new theme, when we will start migrating to vue.js
