### ISSUE TITLE
Bug in user creation

### ISSUE THREAD

**Issue by nosfas** [viralsolani/laravel-adminpanel#87]
Created a new User on the Backend.
With Active, Send Confirmation, and User role checked.

Got the error:
Class 'App\Repositories\Backend\Access\User\UserNeedsConfirmation' not found
…\app\Repositories\Backend\Access\User\UserRepository.php117

Fixed it by calling "use App\Notifications\Frontend\Auth\UserNeedsConfirmation;"

**Comment by bvipul** [comment]
#88 Same error for file UserNeedsConfirmation. would be solved in response to #88.

**Comment by viralsolani** [comment]
@nosfas Yes, we need to use frontend UserNeedsConfirmation in the backend as well. Thanks for the pointing out this issue. its resolved now.
