### ISSUE TITLE
User permission roles

### ISSUE THREAD

**Issue by nosfas** [viralsolani/laravel-adminpanel#88]
A new user with the user role, had no permissions selected bellow.
Clicking the "view Frontend" and the update button, doesn't work.
Clicking the User role again, until the "view Frontend" is selected, and then the update button, works.
But now i have duplicated permissions on the table, because changing roles, duplicates permissions.
Now, I can't remove permissions on the backend.

If I create a user with that role, and remove the default permission, the following error is thrown:
Invalid argument supplied for foreach()
    public function attachPermissions($permissions)
    {
        foreach ($permissions as $permission) {
            $this->attachPermission($permission);
        }
    }

**Comment by bvipul** [comment]
Thanks for pointing out the bug @nosfas, we will fix it as soon as possible.

**Comment by bvipul** [comment]
@nosfas, Sorry but we are not able to understand the issue, can you please elaborate, what problem are you facing, with clear steps to reproduce the issue.

**Comment by nosfas** [comment]
- Selecting permissions individually doesn't work.
- A User with User Role, if you uncheck every permission, throws an error.
- There's also a bug in the permission management, since there are many duplicate permissions if you change the User to others roles. There seems to be no check if the user already has that permission.

**Comment by viralsolani** [comment]
ok, @nosfas. thanks for reporting these issues. we will try to resolve it asap.

**Comment by viralsolani** [comment]
@nosfas all the issues are resolved. Please check once and if you found any other issue then do the report here or please close the ticket. thanks.

**Comment by jobferrera** [comment]
Hello sir, i have a concern though the system is quite working for me very well, but when i created some modules and a user with the roles of the modules i created it doesn't  seem to work. The only thing that works fine are the modules which are default created by you. Thank you in advanced.
